{
    "paging" : <?php print json_encode($this->paginator->params()); ?>,
    "search_result": [
    <?php
    $items = array();
    foreach ($this->files as $file) {
        $file_url = $this->base . '/assets/files/uploads/' . $this->text->cleanForUrl($file->getName()) . '_' . $file->getId() . '.' . $file->getType();
        if (true === in_array($file->getType() , $this->arr_thumbs_formats)) {
            $preview = $this->base . '/assets/files/thumbnails/' . $this->text->cleanForUrl($file->getName()) . '_' . $file->getId() . '_96.' . $file->getType();
        } else if (true === in_array($file->getType() , $this->arr_html_formats)) {
            $preview = $this->base . '/' . $this->theme_path . '/web/images/icons/16px/html.png';
        } else if (true === in_array($file->getType() , $this->arr_formats)) {
            $preview = $this->base . '/' . $this->theme_path . '/web/images/icons/64px/' . $file->getType() . '.png';
        } else {
            $preview = $this->base . '/' . $this->theme_path . '/web/images/icons/64px/default.png';
        }

        $items[] = '{
            "id" : ' . $file->getId() . ',
            "name" : "' . $file->getNameEncoded() . '",
            "file" : "' . $file_url . '",
            "preview" : "' . $preview . '",
            "type" : "' . $file->getType() . '",
            "date" : "' . $file->getCreated() . '",
            "size" : "' . $file->getSize() . '"
        }';
    }
    print implode(',', $items);
    ?>
    ]
}