<div class="ncw-right">
    <div class="ncw-main-tabs">
        <ul class="ncw-main-tabs-container">
            <li class="ncw-main-tab"><a href="#"><?php echo T_('Stats');?></a></li>
        </ul>
        <div class="ncw-main-tab-contents">
            <div class="ncw-main-tab-content">
                <table class="ncw-table">
                    <thead>
                        <tr>
                            <th><?php echo T_('File'); ?></th>
                            <th><?php echo T_('Type'); ?></th>
                            <th><?php echo T_('Language'); ?></th>
                            <th><?php echo T_('Count'); ?></th>
                            <th><?php echo T_('View'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
