<div class="ncw-right">
    <?php print $this->form->create(); ?>
    <?php print $this->form->input("id", array('type' => 'hidden', 'value' => $this->sitetemplate_id)); ?>
    <div class="ncw-main-tabs">
        <ul class="ncw-main-tabs-container">
        	<li class="ncw-option-tab"><?php print $this->html->link(T_('Back'), array('action' => 'all')); ?></li>
            <li class="ncw-main-tab"><a href="#"><?php print T_('Edit sitetemplate'); ?></a></li>
        </ul>
        <div class="ncw-main-tab-contents">
            <div class="ncw-main-tab-content">
                <?php print $this->form->input("name", array('maxlength' => 100, 'title' => T_('Name'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Name')))); ?>
                <?php print $this->form->input("sitetype_id", array('type' => 'select', 'options' => $this->sitetypes, 'title' => T_('Site type'), 'class' => 'ncw-select', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Site type')))); ?>
                <?php print $this->form->input("code", array("type" => "hidden")); ?>
                <div class="codemirror">
                    <?php print $this->form->input("Codemirror.editor", array("type" => "textarea", 'cols' => 20, 'rows' => 30, 'label' => false, "value" => $this->code)); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="ncw-status-action-bar">
        <div class="ncw-status-message"></div>
        <ul class="ncw-actions">
            <li class="ncw-action"><a href="<?php print $this->html->url(array('action' => 'delete', 'id' => $this->sitetemplate_id)); ?>" class="ncw-delete-trigger ncw_delete_icon"><?php print T_('Delete'); ?></a></li>
            <li class="ncw-action"><a href="#" class="ncw-sitetemplate-save-trigger ncw_save_icon"><?php print T_('Save'); ?></a></li>
        </ul>
    </div>
    <?php print $this->form->end(); ?>
</div>