   <?php

$url_pdb2 = Ncw_Configure::read('Project.url');

$login_error = false;
if (true === isset($_POST['sent'], $_POST['login'], $_POST['password']) &&
		$_POST['sent'] == 1) {
	try {
		Ncw_Components_Session::regenerate();

		$fields = array(
			'name' => array('rules' => array('Username'), 'required' => true),
			'password' => array('rules' => array('Password'), 'required' => true)
		);
		// $validator = new Ncw_Validator($fields);
		$data = array();

		$data['name'] = Ncw_Library_Sanitizer::clean($_POST['login']);
		$data['password'] = Ncw_Library_Sanitizer::clean($_POST['password']);

		// $data['name'] = $_POST['login'];
		// $data['password'] = $_POST['password'];
		// list($success, $invalid_fields) = $validator->validate($data);
		// if (true === $success) {
		$obj_user = Core_UserController::validateLogin($data['name'], $data['password']);
		if (true === $obj_user instanceof Core_User) {
			Core_UserController::login($obj_user);

			$usergroup_user = new Core_UsergroupUser();
			$usergroup = $usergroup_user->fetch(
				'list',
				array(
					'fields' => array('Usergroup.name'),
					'conditions' => array(
						'User.id' => $obj_user->getId(),
						'Usergroup.parent_id' => 20
					),
					'LIMIT' => 1
				)
			);

			$usr_role = array_pop(explode(';', array_pop($usergroup)));

			Ncw_Components_Session::writeInAll(
				'PDB',
				array(
					'USRID' => $obj_user->getId(),
					'USRNAME' => $obj_user->getName(),
					'ROLE' => $usr_role,
					'LANG' => $language_code,
				)
			);
		}

		if (true === isset($user['mainid'], $user['un']) &&
				(int) $user['mainid'] > 0) {
			$login = new Tpe_Login();
			$login->setSessId(session_id());
			$login->setUser($user['un']);
			$login->save(false);
			Ncw_Components_Session::writeInAll('tpe_login', $user['un']);
			Ncw_Components_Session::writeInAll('tpe_login_id', $login->getId());
		}
		if (false == isset($language)) {
			if (true == isset($_GET['ls'])) {
				$language = $_GET['ls'];
			}
		}
		if (Ncw_Configure::read('App.ssl') == 'true') {
			$url_location = $url_pdb2 . '/include/login.php';
			$url_location = $url_pdb2 . '/index.php?url=' . $language . '/products/loginktpepdb-215';
		} else {
			$url_location = $url_pdb2 . '/include/login.php';
			$url_location = $url_pdb2 . '/index.php?url=' . $language . '/products/loginktpepdb-215';
		}
		if (!strstr($_SERVER['REQUEST_URI'], '/product/')) {
			header('Location: ' . $this->here . '');

			echo '<script>
									location.href="' . $url_location . '";
									</script>';
			// unset($_SESSION['PDB']['USRID']);
			// header('Location: ' . $url_location);
			// exit;
		} else {
			echo '<script>
									location.href="' . $url_location . '";
									</script>';
			// header('Location: https://www.kraiburg-tpe.com/product');
			// exit;
		}
	} catch (Exception $e) {
		print $e->getMessage();
	}
}
?>


<?php

if (false === Ncw_Components_Session::checkInAll('PDB')) {
	Ncw_Components_Session::writeInAll(
		'PDB',
		array(
			'ROLE' => 0,
			'LANG' => $language_code,
		)
	);
} else {
	$_SESSION['PDB']['LANG'] = $language_code;
}

// var_dump($_SESSION);

if (true === isset($_GET['logout']) && 1 == $_GET['logout']) {
	$tpe_id = Ncw_Components_Session::readInAll('tpe_login_id');
	$login = new Tpe_Login();
	$login->setId($tpe_id);
	$login->delete(false);
	Ncw_Components_Session::deleteInAll('tpe_login');
	Ncw_Components_Session::deleteInAll('tpe_login_id');
	Ncw_Components_Session::deleteInAll('PDB');
	Ncw_Components_Session::writeInAll('logout_message', true);
	Core_UserController::logout();
	Ncw_Components_Session::regenerate();
	// if (!strstr($_SERVER['REQUEST_URI'], '/product/')) {
	//    header('Location: ' . $this->here);
	// } else {
	header('Location: ' . $url_pdb2);
	// }
	exit();
}
?>
<?php
$login = Ncw_Components_Session::readInAll('PDB');
// strlen($login['USRNAME']) > 3
// var_dump($_SESSION['PDB']['USRID']);

if (true == strstr($_SERVER['REQUEST_URI'], '/loginktpepdb') || true === Ncw_Components_Session::checkInAll('tpe_login')) {
	?>

<section class="loginpdbcontainer">
	<div style="background-image:url('https://www.kraiburg-tpe.com/sites/default/files/assets/pattern/transparent.png')" class="paragraph clearfix paragraph--type--section paragraph--view-mode--default row center-content section-bottom-space-big color-scheme-transparent">
		<div class="paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-transparent col-sm-16">
			
			<div class="paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-transparent col-sm-24">
				<div style="background-image:url('https://www.kraiburg-tpe.com/sites/default/files/assets/pattern/transparent.png')" class="pattern-outer">
					<div class="bigspace-wrapper clearfix pattern-inner">
						<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
							<h1 class="headline-1 text-align-center">
							<?php if (false == isset($_SESSION['PDB']['USRID'])) { ?>
							<p><span><?php echo Wcms_ContentboxController::getContenbox('login', $language_id); ?></span></p></h1>
							<?php } else { ?>
							<p><span><?php echo Wcms_ContentboxController::getContenbox('logout', $language_id); ?></span></p></h1>
							<?php } ?>
						</div>
					</div>
				</div>
			</div>
			
			<div style="background-image:url('https://www.kraiburg-tpe.com/sites/default/files/assets/pattern/transparent.png')" class="pattern-outer">
				<div class="smallspace-wrapper clearfix pattern-inner">
					<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
						<p class="text-align-justify">
							<?php echo Wcms_ContentboxController::getContenbox('pdb2-after-login', $language_id); ?>
  					</p>
					</div>
				</div>
			</div>
  	</div>
	</div>
	
	
	
    
  <div class="row ct-u-padding-top-40 ct-u-padding-bottom-80 pdb-search-header light-font">
  	<div class="container ">
			<div class="row ">

			
			
    	<?php
		if (false == isset($_SESSION['PDB']['USRID'])) {
			// var_dump($_SESSION['PDB']['USRID']);
			?>
				<div class="col-sm-9 col-xs-3"></div>
				<div class="col-sm-7 col-xs-18">
					<h3><?php print Wcms_ContentboxController::getContenbox('login', $language_id); ?></h3>
					<?php

					if (true == isset($_GET['url'])) {
						$arr_url = explode('/', $_GET['url']);
						$language = $arr_url[0];
					} else {
						$language = 'en';
					}

					if (Ncw_Configure::read('App.ssl') == 'true') {
						$form_link = $url_pdb2 . '/index.php?url=' . $language . '/products/loginktpepdb-215';
					} else {
						$form_link = $url_pdb2 . '/index.php?url=' . $language . '/products/loginktpepdb-215';
					}
					if (Ncw_Configure::read('App.ssl') == 'true') {
						?>
							<form id="product-database-login" class="tpe-login-form" method="post" action="<?php print $form_link; ?>">
						<?php
					} else {
						?>
							<form id="product-database-login" class="tpe-login-form" method="POST" action="<?php print $form_link; ?>">
						<?php
					}
					?>
							<input type="hidden" name="sent" value="1" />

								<div class="input-group">
									<label for="user"><?php print Wcms_ContentboxController::getContenbox('user', $language_id); ?>:</label>
									<input type="text" class="ncw-login-to-pdb" id="user" name="login" tabindex="997" value="" style="height: 40px !important; font-size: 25px !important;" />
								</div>
								<div class="input-group">
									<label for="password"><?php print Wcms_ContentboxController::getContenbox('password', $language_id); ?>:</label>
									<input type="password" class="ncw-login-to-pdb" id="password" name="password" tabindex="998" value="" style="height: 40px !important; font-size: 25px !important; " class="tpepdb2_sf tpe-pdb-search-extsearch" />
								</div>
								
								<div class="input-group">
									<input type="submit" value="<?php print Wcms_ContentboxController::getContenbox('login', $language_id); ?>" class="submit" tabindex="999" style="height: 40px !important; font-size: 25px !important;" />
								</div>
								<div class="input-group">
								<br /><a href="https://pdb.kraiburg-tpe.com/index.php?url=en/products/lost-password-24"><?php print Wcms_ContentboxController::getContenbox('lost-pwd', $language_id); ?>?</a>
								</div>
					</form>
				</div>
          
					<?php
		} else {
			?>
						<script>
							jQuery(document).ready(
									function () {
										removeChat();
									}
							);
						</script>

				<div class="row">
				

					<div class="col-md-24">
						<div class="row">
							<div class="col-md-6 col-xs-6"></div>
								
							<div class="col-md-12">
							<?php print Wcms_ContentboxController::getContenbox('logged-in', $language_id) . ' ' . $login['USRNAME'] ?><br />
							</div>
						</div>
						<div class="row">
							<div class="col-md-6  col-xs-6"></div>
							<div class="col-md-12 col-xs-15">
							<h3><?php // print Wcms_ContentboxController::getContenbox('logout', $language_id); ?></h3>
						  </div>
						</div>
						<div class="row">
							<div class="col-md-6 col-xs-6"></div>
							<div class="col-md-6 col-xs-12">
								 <form id="product-database-login" class="tpe-login-form" method="post" action="<?php echo $url_pdb2; ?>/index.php?url=en/products/loginktpepdb-215&logout=1">
								<div class="input-group">
									<input type="submit" value="<?php print Wcms_ContentboxController::getContenbox('logout', $language_id); ?>" class="submit" tabindex="999"  />
								</div>
								</form>
							</div>
							<div class="col-md-6 ">
								<div class="col-md-6 col-xs-6"></div>
							<form class="tpe-login-form col-xs-12">

								<div class="input-group">
									<?php if (Ncw_Configure::read('App.ssl') == 'true') { ?>
									<input type="button" value="<?php print Wcms_ContentboxController::getContenbox('compound-id-search', $language_id); ?> " class="submit" tabindex="999" onclick="javascript: top.location.href='<?php echo $url_pdb2; ?>'" />
									<?php } else { ?>
									<input type="button" value="<?php print Wcms_ContentboxController::getContenbox('compound-id-search', $language_id); ?> " class="submit" tabindex="999" onclick="javascript: top.location.href='<?php echo $url_pdb2; ?>'" />
									<?php } ?>
								</div>

							</form>
						</div>
					 </div>
				  </div>
				</div>
				<?php } ?>
		
			</div>
		</div> <!-- End Container -->
				</div>
    </section>





 

    
    

<?php } ?>
