<section class="loginpdbcontainer">
<?php
if (false == isset($_GET['resetpassword'])) {
	?>

	<div style="background-image:url('https://www.kraiburg-tpe.com/sites/default/files/assets/pattern/transparent.png')" class="paragraph clearfix paragraph--type--section paragraph--view-mode--default row center-content section-bottom-space-big color-scheme-transparent">
		<div class="paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-transparent col-sm-16">
			
			<div class="paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-transparent col-sm-24">
				<div style="background-image:url('https://www.kraiburg-tpe.com/sites/default/files/assets/pattern/transparent.png')" class="pattern-outer">
					<div class="bigspace-wrapper clearfix pattern-inner">
						<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
							<h1 class="headline-1 text-align-center">
														<p><span><?php print Wcms_ContentboxController::getContenbox('lost-pwd', $language_id); ?></span></p></h1>
													</div>
					</div>
				</div>
			</div>
			
			<div style="background-image:url('https://www.kraiburg-tpe.com/sites/default/files/assets/pattern/transparent.png')" class="pattern-outer">
				<div class="smallspace-wrapper clearfix pattern-inner">
					<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
          <p>
           
        </p>
					</div>
				</div>
			</div>
  	</div>
	</div>
	
	
	
    
  <div class="row ct-u-padding-top-40 ct-u-padding-bottom-80 pdb-search-header light-font">
  	<div class="container ">
			<div class="row ">
    		<div class="col-sm-9 col-xs-3"></div>
				<div class="col-sm-7 col-xs-18">
					<h3><?php print Wcms_ContentboxController::getContenbox('lost-pwd', $language_id); ?></h3>
					<form id="product-database-login" class="tpe-login-form" method="post" action="#" style="display: block;">
						<input type="hidden" name="sent" value="1">

						<div class="input-group">
							<label for="user">E-Mail:</label>
							<input type="email" class="ncw-passwort-email" id="user" name="login" tabindex="997" value="" style="height: 40px !important; font-size: 25px !important;" placeholder="Your E-Mail">
						</div>
								
						<div class="input-group">
							<label style="color: #f00; display: none;" class="error-mail-nicht-vorhanden"><?php print Wcms_ContentboxController::getContenbox('lost-pwd-this-email', $language_id); ?></label>
							<input type="button" value="<?php print Wcms_ContentboxController::getContenbox('send', $language_id); ?>" class="submit" tabindex="999" style="height: 40px !important; font-size: 25px !important;" onclick="resetPasswordSendMail();">
						</div>
					</form>
					<div class="message-email-versandt" style="display: none;">
						<?php print Wcms_ContentboxController::getContenbox('lost-pwd-a-email', $language_id); ?><br /><a href="https://pdb.kraiburg-tpe.com"><?php print Wcms_ContentboxController::getContenbox('send', $language_id); ?></a>
					</div>
				</div>
          
							
			</div>
		</div> <!-- End Container -->
		</div>
    
		<script>
			function resetPasswordSendMail() {
				var email = $('.ncw-passwort-email').val();
				
				var str_url = "admin/tpepdb2/ajax/resetPasswordSendMail?email=" + email;

				//alert(str_url);

					$.get(
						baseproject + str_url,
						function (html) {
							//	alert(html);
							if (html == 'error-mail-nicht-vorhanden') {
								$('.error-mail-nicht-vorhanden').show();
							}
							if (html == 'true') {
								$('#product-database-login').hide();
								$('.message-email-versandt').show();
							}
							//	console.log(html);
						}
					);
				
			}
	  </script>
	
<?php
} else {
	if (strlen($_GET['resetpassword']) > 0) {
?>
	<div style="background-image:url('https://www.kraiburg-tpe.com/sites/default/files/assets/pattern/transparent.png')" class="paragraph clearfix paragraph--type--section paragraph--view-mode--default row center-content section-bottom-space-big color-scheme-transparent">
		<div class="paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-transparent col-sm-16">
			
			<div class="paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-transparent col-sm-24">
				<div style="background-image:url('https://www.kraiburg-tpe.com/sites/default/files/assets/pattern/transparent.png')" class="pattern-outer">
					<div class="bigspace-wrapper clearfix pattern-inner">
						<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
							<h1 class="headline-1 text-align-center">
														<p><span><?php print Wcms_ContentboxController::getContenbox('lost-pwd-enter-a-pwd', $language_id); ?></span></p></h1>
													</div>
					</div>
				</div>
			</div>
			
			<div style="background-image:url('https://www.kraiburg-tpe.com/sites/default/files/assets/pattern/transparent.png')" class="pattern-outer">
				<div class="smallspace-wrapper clearfix pattern-inner">
					<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
          <p>
            <?php print Wcms_ContentboxController::getContenbox('lost-pwd-enter-a-pwd', $language_id); ?>
						
        </p>
					</div>
				</div>
			</div>
  	</div>
	</div>
	
	
	
    
  <div class="row ct-u-padding-top-40 ct-u-padding-bottom-80 pdb-search-header light-font">
  	<div class="container ">
			<div class="row ">

			
			
    					<div class="col-sm-9 col-xs-3"></div>
				<div class="col-sm-7 col-xs-18">
					<h3><?php print Wcms_ContentboxController::getContenbox('lost-pwd-enter-a-pwd', $language_id); ?></h3>
						<form id="product-database-login" class="tpe-login-form" method="post" action="#" style="display: block">
													<input type="hidden" name="sent" value="1">

								<div class="input-group">
									<label for="user">new Password</label>
									<input type="text" class="ncw-passwort-email" id="user" name="login" tabindex="997"  style="height: 40px !important; font-size: 25px !important;" placeholder="********" value="">
								</div>
								
								<div class="input-group">
									<label style="color: #f00; display: none;" class="error_passwort_unsicher"><?php print Wcms_ContentboxController::getContenbox('lost-pdw-8-chars', $language_id); ?></label>
									<label style="color: #f00; display: none;" class="error_link_abgelaufen">Der Link ist abgelaufen. Bitte geben Sie ihre E-Mail <a href="https://pdb.kraiburg-tpe.com/index.php?url=en/products/lost-password-24">hier</a> noch einmal ein.</label>
									<input type="button" value="Passwort ändern" class="submit" tabindex="999" style="height: 40px !important; font-size: 25px !important;" onclick="resetPassword();">
								</div>
					</form>

				</div>
     
							
			</div>
		</div> <!-- End Container -->
		</div>
	
		<script>
			function resetPassword() {
				var password = $('.ncw-passwort-email').val();
				
				var str_url = "admin/tpepdb2/ajax/resetPassword?password=" + password + "&hashcode=<?php echo $_GET['resetpassword']; ?>";
				$.get(
					 baseproject + str_url,
					 function (html) {
						//	alert(html);
							if (html == 'error_passwort_unsicher') {
								$('.error_passwort_unsicher').show();
							}
							if (html == 'error_link_abgelaufen') {
								$('.error_link_abgelaufen').show();
							}
							if (html == 'true') {
								location.href = "https://pdb.kraiburg-tpe.com/?url=en/products/loginktpepdb-215";
							}
						}
				);
			}
	  </script>
	
<?php
	} else {
		break;
	}
}
?>
</section>