<div {if.admin}id="{component.id}"{/if} class="box_right {admin.class}">
  <h3 id="{shorttext.1.id}" class="{admin.content.class}">{shorttext.1}</h3>
  <div id="{text.1.id}" class="{admin.content.class}">{text.1}</div>
</div>
{shorttext.1.width=224}
{shorttext.1.height=36}
{shorttext.1.background=url(assets/wcms/files/bg_box_right_h.gif) no-repeat 0 0}
{shorttext.1.mode=simple}
{text.1.width=224}
{text.1.background=url(assets/wcms/files/bg_box_right.gif) repeat-x 0 bottom #ececed}
{text.1.mode=advanced}

{component.move-left=-16}
