<div {if.admin}id="{component.id}"{/if} class="vertical_gallery {admin.class}">
<h2 id="{shorttext.1.id}" class="{admin.content.class}">{shorttext.1}</h2>
<div class="vertical_content">
  <img class="vertical_content_prev" src="assets/wcms/files/vertical_gallery_prev.gif" alt="" title="" />
    <div>
       <ul id="{area.4.id}" class="{area.admin.class.sub}">{area.4.noadmin}</ul>
    </div>
  <img class="vertical_content_next" src="assets/wcms/files/vertical_gallery_next.gif" alt="" title="" />
</div>
</div>
{shorttext.1.width=192}
{shorttext.1.height=}
{shorttext.1.background=url(assets/wcms/files/bg_vertical_gallery_h.gif) no-repeat 0 0}

{component.move-left=-16}
<?php $gallery = true; ?>
