<?php



$headline = "<b>" . $compound["name"] . "</b>";
if (true === $is_pdf) {
    $headline = remove_bold($headline);
}
if ($serie["name"] != "") {
	if ($language_id == 8 || $language_id == 5) {
		$headline .=  " (" . Wcms_ContentboxController::getContenbox('pdb---series', $language_id) . ' ' . $serie["name"] . ')';
	} else {
		$headline .=  " (" . $serie["name"] . ' ' . Wcms_ContentboxController::getContenbox('pdb---series', $language_id) . ')';
	}
}
?>
<table style="width:100%" cellspacing="0" cellpadding="0">
    <tr style="background-color: #fff;">
        <td style="height: 40px; width: 70%;"><?php print td_value($headline,  ((int) $font_size_table + 4) . 'px', false, '#fff', '18px', '10px'); ?></td>
        <td style="background-color: #ffffff; border-top: 1px solid #ccc;border-bottom: 1px solid #134d93; height: 40px; width: 30%; background: #fff;">
            <table style="width:100%" cellspacing="10" cellpadding="0"><tr><td style="color: #18529D; font-size: <?php print (int) $font_size_table + 4;?>px;">
                <?php 
        				    if ($language_id != 3 || strlen($brand["name_zh"]) < 1) { // 3 ist Chinesisch und soll den eintrag name_zh benutezn
								     	print str_replace('®', '<sup>®</sup>', $brand["name"]);
								    } else {
								    	print str_replace('®', '<sup>®</sup>', $brand["name_zh"]);
								    }
								?>
            	</td></tr></table>
        </td>
    </tr>
</table>
<br />
<?php if (true === $is_pdf) { ?><br /><?php } ?>
