<?php

$layoutmode = 2021;
if ($_SERVER['REMOTE_ADDR'] == Ncw_Configure::read('developer_internal_ip')) {
	$layoutmode = 2021;
}
?>

<?php if (true === $is_pdf) { ?>
<?php ob_start(); ?>
<?php  // Wenn nicht Verarbeitungshinweis
	if ($_SESSION['datasheetmode'] != 'pg') {
		if ($serie['brand_id'] == 4 || $arr_brandname['brandnameen'] == 'THERMOLAST® M') {
			$_SESSION['storageMonth'] = 24;
			// Für PDF Druck wird das Ganze in vendor/TpePdbPdf.php abgebildet
			?>

		<table style="font-size: 11px;" cellpadding="10" ><tr><td><?php print Wcms_ContentboxController::getContenbox('pdb2-datasheet-footer-storage-24m', $language_id); ?><br /><br /><?php print Wcms_ContentboxController::getContenbox('pdb2-for-further-information', $language_id); ?></td></tr></table>
		<?php
		} else {
			$_SESSION['storageMonth'] = 12;
		?>
		<table style="font-size: 11px;" cellpadding="10" ><tr><td><?php print Wcms_ContentboxController::getContenbox('pdb2-datasheet-footer-storage', $language_id); ?><br /><br /><?php print Wcms_ContentboxController::getContenbox('pdb2-for-further-information', $language_id); ?></td></tr></table>
		<?php
		}
		?>
<?php } else { ?>
 <br /><br /><br /><br /><br /><br /><br /><br />
<?php } ?>
<?php if ($language_id == 3 || $language_id == 7 || $language_id == 10 || $language_id == 11) { ?>
<table style="font-size: 10px;" cellpadding="6" >
<?php } else { ?>
<table style="font-size: 10px;" cellpadding="6" >
<?php } ?>

	<tr>
	<td style="background-color: #f3f3f3;border-right: 3px solid #ffffff; width: 167px">
		<?php print Wcms_ContentboxController::getContenbox('datenblatt-adr-euro', $language_id); ?>
	</td>
	<td style="background-color: #f3f3f3;border-right: 3px solid #ffffff; width: 210px">
		<?php print Wcms_ContentboxController::getContenbox('datenblatt-adr-asia', $language_id); ?>
	</td>
	<td style="background-color: #f3f3f3;border-right: 3px solid #ffffff; width: 167px">
		<?php print Wcms_ContentboxController::getContenbox('datenblatt-adr-usa', $language_id); ?>
		</td>
	  <td style="background-color: #f3f3f3; width: 146px" >
			<table>
				<tr>
					<td style="width: 85px; line-height: 12.5px;"><b>WhatsApp<br />Support</b><br /><br />
					<span style="margin-top: 20px;">+49 172 8533045</span></td>
					<td style="width: 50px"><img src="/assets/wcms/files/WhatsAppQRCode.png" style="float: left; padding-top: 4px;" width="49" height="49" /></td>
				</tr>
			</table>

		
		</td>
	</tr>
</table>
<?php $footer_content = ob_get_clean(); ?>
<?php if (true === $is_pdf) { ?>
	<?php $pdf->footer_content_s1 = $footer_content; ?>
<?php } ?>
	<?php ob_start(); ?>
	<?php
	// $footer = Wcms_ContentboxController::getContenbox('pdb---datasheet---footer', $language_id);
	if (false === $is_pdf) {
		//    $footer = str_replace("<br />", "", $footer);
	}
	?>
	<?php if (false === $is_pdf) { ?><br /><?php } ?>



	<table style="width:100%;" cellpadding="0" cellspacing="0">
		<?php if ($layoutmode != 2021) { ?>
	    <tr>
	        <td style="font-size: 11px;"><?php print str_replace('date(Y)', date('Y'), $footer); ?><br /><br /><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---disclaimer', $language_id); ?><br /><?php if (false === $is_pdf) { ?><br /><?php } ?></td>
	    </tr>
		<?php } ?>
	    <tr>
	        <td><table style="width:100%;" cellpadding="0" cellspacing="0">
	                <tr>
	                    <td style="font-size: 11px;"><?php print date(Wcms_ContentboxController::getContenbox('pdb---datasheet---date', $language_id), time()); ?>
	                    <?php if (true === $is_pdf) { ?><?php print str_replace('date(Y)', date('Y'), Wcms_ContentboxController::getContenbox('pdb---datasheet---pdf-footer', $language_id)); ?><?php } ?>
												</td>
	                </tr>
	            </table>
	        </td>
	    </tr>
	</table>
	<?php $footer_content = ob_get_clean(); ?>
	<?php if (true === $is_pdf) { ?>
	    <?php $pdf->footer_content = $footer_content; ?>
	<?php } else { ?>
	    <?php print $footer_content; ?>
	<?php } ?>
<?php } ?>