<?php ob_start(); ?>

<?php

$layoutmode = 2021;

?>


<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td style="height: 70px"><img src="<?php print ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'images' . DS . 'tpe-logo-b-2019.png'; ?>" height="170" /></td>
        

      
       
        <!--<td align="right">
            <table cellpadding="0" cellspacing="0">
                <tr>
                    <td style="height: 28px;">&nbsp;</td>
                </tr>
                <tr>
                    <td><b style="font-size:16px;">

                    <?php
					if ($layoutmode == 2021) {
						print Wcms_ContentboxController::getContenbox('label-prodctinformation', $language_id);
					} else {
						if ($type == 'serie' || $compound['status'] == 'portfolio') {
							print Wcms_ContentboxController::getContenbox('pdb---datasheet---datasheet', $language_id);
						} else {
							// print Wcms_ContentboxController::getContenbox('pdb---datasheet---test-report', $language_id);
							print Wcms_ContentboxController::getContenbox('pdb---datasheet---datasheet', $language_id);
						}
					}

					?>
</b>
                    </td>
                </tr>
            </table>
        </td>-->
    </tr>
    <?php if ($_SESSION['datasheetmode'] != 'pg' && $compound['status'] != 'non_portfolio') { ?>

    <?php } ?>
</table>

<br />
<br />
<br /><br /><br /><br /><br />
<?php
if ($type == 'serie') {
	include_once ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'elements' . DS . 'pdf_templates' . DS . 'serie_headline.phtml';
} else {
	include_once ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'elements' . DS . 'pdf_templates' . DS . 'compound_headline.phtml';
}
?>
<?php

// Wenn Verarbeitungshinweis
if ($_SESSION['datasheetmode'] == 'pg') {
	$arr_processingnote_type = array();

	$processing_type = $processingnotes[0]['type'];
	if ($processing_type == 'processing_im') {
		$processing_type = 'injection';
	}
	if ($processing_type == 'processing_ex') {
		$processing_type = 'extrusion';
	}

	$processingnotes_all = $this->getCompoundProcessing($compound['id'], $language_id);

	// var_dump($processingnotes_all);
	foreach ($processingnotes as $processingnote_type => $processingnote) {
		$arr_processingnote_type[] = $processingnote_type;
	}
	$processingnotes = $processingnotes_all['processing_im'];
	$processing_type = $processingnotes[0]['type'];
	if ($processing_type == 'processing_im') {
		$processing_type = 'injection';
	}
	if ($processing_type == 'processing_ex') {
		$processing_type = 'extrusion';
	}
	// $pdf->header_description = '<div style="font-size: 16px; color: #055499;">' . Wcms_ContentboxController::getContenbox('pdb---datasheet---processing-guideline', $language_id) . '</div><div style="font-size: 16px; color: #4D4D4F;">' . 					$arr_processingnote_type[1] . '</div>';
	// $processing_type = 'injection';
	if ($language_id == 11) {
		$pdf->header_type = '<div style="font-size: 18px; color: #fff;"><b>' . Wcms_ContentboxController::getContenbox('pdb---datasheet---processing-guideline', $language_id) . '</b> (' . Wcms_ContentboxController::getContenbox($processing_type, $language_id) . ')</div>';
	} else {
		$pdf->header_type = '<div style="font-size: 22px; color: #fff;"><b>' . Wcms_ContentboxController::getContenbox('pdb---datasheet---processing-guideline', $language_id) . '</b> (' . Wcms_ContentboxController::getContenbox($processing_type, $language_id) . ')</div>';
	}
} else {  // Normales Datenblatt
	if ($compound['status'] != 'non_portfolio') {
		$pdf->header_type = '<div style="font-size: 22px; color: #fff;"><b>' . Wcms_ContentboxController::getContenbox('label-prodctinformation', $language_id) . '</b></div>';
	} else {
		$pdf->header_type = '<div style="font-size: 22px; color: #fff;"><b>' . Wcms_ContentboxController::getContenbox('pdb---datasheet---datasheet', $language_id) . '</b></div>';
	}
	if ($language_id == 3) {  // China
		$pdf->header_type2 = '<div style="font-size: 22px; color: #fff; line-height: 23px;"><b>凯柏胶宝<br>' . Wcms_ContentboxController::getContenbox('pdb---datasheet---datasheet', $language_id) . '</b></div>';
	} else {
		$pdf->header_type2 = '<div style="font-size: 22px; color: #fff;"><b>' . Wcms_ContentboxController::getContenbox('pdb---datasheet---datasheet', $language_id) . '</b></div>';
	}

	if ($language_id == 2 || $language_id == 4 || $language_id == 5 || $language_id == 8 || $language_id == 11) {
		$cellpadding_anmerkung = '4';
		$line_height_anmerkung = '1.1';
	} else if ($language_id == 3) {  // ZH
		$cellpadding_anmerkung = '12';
		$line_height_anmerkung = '1.4';
		$pdf->header_top = 2;
	} else if ($language_id == 10) {  // KR
		$cellpadding_anmerkung = '11';
		$line_height_anmerkung = '1.3';
	} else {
		$cellpadding_anmerkung = '10';
		$line_height_anmerkung = '1.2';
	}
	$pdf->header_description_anmerkung = '<div style="font-size: 15px; color: #333; border: 1px solid #134d93; width: 273px; line-height: ' . $line_height_anmerkung . '"><table border="0" cellpadding="' . $cellpadding_anmerkung . '"><tr><td>' . trim(Wcms_ContentboxController::getContenbox('diclaimer-s', $language_id)) . '</td></tr></table></div>';
}

$headline = '<div style="font-size: 18px; color: #fff; width: 350px;">';
if ($type == 'serie') {
	if ($serie['name'] != '') {
		if ($language_id == 8 || $language_id == 5 || $language_id == 11) {
			$headline .= '' . Wcms_ContentboxController::getContenbox('pdb---series', $language_id) . ' ' . $serie['name'] . '';
		} else {
			$headline .= '<b>' . $serie['name'] . '</b> ' . Wcms_ContentboxController::getContenbox('pdb---series', $language_id) . '';
		}
	}
} else {
	$headline .= '<b>' . $compound['name'] . '</b> ';
	if ($serie['name'] != '') {
		if ($language_id == 8 || $language_id == 5 || $language_id == 11) {
			$headline .= ' (' . Wcms_ContentboxController::getContenbox('pdb---series', $language_id) . ' ' . $serie['name'] . ')';
		} else {
			$headline .= ' (' . $serie['name'] . ' ' . Wcms_ContentboxController::getContenbox('pdb---series', $language_id) . ')';
		}
	}
}

// Einbau am 05.08.2025 zuruf Henning

$arr_brandname = $this->getCompoundBrandname($compound['id']);  // Holt den Brandnamen in zh und eng
if (strlen(trim($arr_brandname['brandnameen'])) < 2) {  // Wenn im Compound kein Brandname vorhanden ist
	$arr_brandname = $this->getBrandname($serie['brand_id']);  // Holt den Brandnamen in zh und eng
}
if ($language_id != 3) {
	$brandname = $brand['name'];
	if (strlen($arr_brandname['brandnameen']) > 1) {
		$brandname = ' | ' . $arr_brandname['brandnameen'];
	} else if (strlen(trim($brand['name'])) > 1) {
		$headline .= ' | ' . $brand['name'];
	}
} else {  // 3 ist Chinesisch und soll den Eintrag name_zh benutzen
	$brandname = $brand['name_zh'];
	if (strlen($arr_brandname['brandnamezh']) > 1) {
		$brandname = ' | ' . $arr_brandname['brandnamezh'];
	} else if (strlen(trim($brand['name_zh'])) > 1) {
		$headline .= ' | ' . $brand['name_zh'];
	}
}
$headline .= str_replace('®', '<sup>®</sup>', $brandname);
$headline .= '</div>';

// if ($_SERVER["REMOTE_ADDR"] =='62.154.179.198') {
// $headline .=  " (" . $serie["name"] . ' ' . Wcms_ContentboxController::getContenbox('pdb---series', $language_id) . ')';

$str_serie = '';

if ($language_id == 2) {
	$str_serie = 'Serie';
	if (strlen(trim($serie['name'])) < 1) {
		$str_serie = '&nbsp;';
	}
	$headline = '<table style="color: #ffffff;" boder="0" cellpadding="0" cellspacing="0"><tr style="font-size: 12px;"><td style="color: #ffffff;">Markenname</td><td>Compoundbezeichnung</td><td>' . $str_serie . '</td></tr><tr style="font-size: 16px;"><td>' . $brandname . '</td><td>' . $compound['name'] . '</td><td>' . $serie['name'] . '</td></tr></table>';
} else {
	$str_serie = 'Series';
	if (strlen(trim($serie['name'])) < 1) {
		$str_serie = '&nbsp;';
	}
	if ($language_id == 3) {
		$str_serie = '&nbsp;';
		$headline = '<table style="color: #ffffff;" boder="0" cellpadding="0" cellspacing="0"><tr style="font-size: 12px;"><td style="color: #ffffff;">&nbsp;</td><td>&nbsp;</td><td>' . $str_serie . '</td></tr><tr style="font-size: 16px;"><td>' . $brandname . '</td><td>' . $compound['name'] . '</td><td>' . $serie['name'] . '</td></tr></table>';
	} else {
		$headline = '<table style="color: #ffffff;" boder="0" cellpadding="0" cellspacing="0"><tr style="font-size: 12px;"><td style="color: #ffffff;">Brand Name</td><td>Product Code</td><td>' . $str_serie . '</td></tr><tr style="font-size: 16px;"><td>' . $brandname . '</td><td>' . $compound['name'] . '</td><td>' . $serie['name'] . '</td></tr></table>';
	}
}

// $headline =  'Brand Name';
// }

$pdf->header_name = '<div style="font-size: 20px; color: #fff;">' . $headline . '</div>';

if ($type == 'serie') {
	$pdf->pdf_mode = 'series';
	$font_size_symbol = 14;
	$line_height_symbol = 19;
	if (strlen($serie['description']) > 10) {
		$text_grauer_kasten_pdf = $serie['description'];
		$text_grauer_kasten_pdf = str_replace(array('<p>', '</p>', '<P>', '</P>'), array('', ' '), $text_grauer_kasten_pdf);
	} else {
		$text_grauer_kasten_pdf = $this->getSerieDescription($serie['id'], $language_id);
	}
	$text_grauer_kasten_pdf = trim(str_replace(array('<p>', '</p>', '<P>', '</P>'), array('', ' '), $text_grauer_kasten_pdf));
} else {
	$font_size_symbol = 14;
	$line_height_symbol = 19;
	$_SESSION['compound_status'] = false;
	// Abfrage ob Seriencompound, wenn nicht wird in der Footer PDF der Lagerhinweis auf die 1. Seite gedruckt
	// $pdf->compoundStatusFooter dient nur diesem Zweck
	// Wird evtl. in der compound_properties.phtml überschrieben wenn mehr als 6 Compoundeigsnschaften
	if (strlen(trim($serie['description'])) < 10) {
		$pdf->compoundStatusFooter = 'non_portfolio';
	}
	if ($_SESSION['datasheetmode'] == 'datasheet' && $compound['status'] != 'non_portfolio') {
		// $pdf->compound_status = 'non_portfolio';
		if (strlen(trim($this->getCompoundDescription($compound['id'], $language_id))) < 2) {
			$text_grauer_kasten = trim(str_replace(array('<p>', '</p>', '<P>', '</P>'), array('', ' '), $serie['text1']));
		} else {
			$text_grauer_kasten = $this->getCompoundDescription($compound['id'], $language_id);
		}
	}
}

$pdf->header_content = ob_get_clean();

?>