
<tcpdf method="AddPage" />
<?php // include_once ASSETS . DS . "tpepdb2" . DS . "templates"  . DS . "functions.php"; ?>

<?php $type = "serie"; ?>
<?php $id = $serie["id"]; ?>
<?php $name = $serie["name"]; ?>
<?php $documents = $serie["documents"]; ?>

<?php include ASSETS . DS . "tpepdb2" . DS . "templates" . DS . "pdf_templates" . DS . "header.phtml"; ?>


<?php include ASSETS . DS . "tpepdb2" . DS . "templates" . DS . "pdf_templates" . DS . "footer.phtml"; ?>