<?php if (true === $is_pdf) { 


?>


<?php if (true === $is_pdf) { ?><br /><?php } ?>


<?php 
} else { // Ende PDF Anfang HTML
?>
<?php

$pdb_url = 'https://test.kraiburg-tpe.com';
$website_url = 'https://www.kraiburg-tpe.com';

include_once ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'elements' . DS . 'userstate.phtml';
	
?>
<section class="serie">
  <div class="container">
    <div class="row">
			<div class="bigspace-wrapper clearfix pattern-inner">
				<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
					<h2 class="headline-2 text-align-center">
						<?php if ($language_id == 8 || $language_id == 5 || $language_id == 11 || $language_id == 4) { ?> 
							<?php print Wcms_ContentboxController::getContenbox('pdb---series', $language_id) . ' ' . $serie["name"]; ?>
							<?php } else { ?>
							<?php print $serie["name"] . ' ' .  Wcms_ContentboxController::getContenbox('pdb---series', $language_id); ?>
							<?php } ?>
							<?php 
						?>
					</h2>
					<h4 class="subheadline text-align-center">
						<strong>
							<?php 
        				    if ($language_id != 3 || strlen($brand["name_zh"]) < 1) { // 3 ist Chinesisch und soll den eintrag name_zh benutezn
								     	print str_replace('®', '<sup>®</sup>', $brand["name"]);
								    } else {
								    	print str_replace('®', '<sup>®</sup>', $brand["name_zh"]);
								    }
								?>
						</strong>
						<?php print $serie["description"]; ?>
					<strong><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---processing-method', $language_id); ?>:</strong> 
						<?php
							$processingnotes_all = $this->getSerieProcessing($serie['id']);
							//var_dump($processingnotes_all);
							$str_processingnote_type = '';
							if (true == isset($processingnotes_all['processing_im']) ){
								$processing_type = 'injection';
								$str_processingnote_type = Wcms_ContentboxController::getContenbox($processing_type, $language_id);
							}
							if (true == isset($processingnotes_all['processing_ex']) ){
								$processing_type = 'extrusion';
								if (strlen($str_processingnote_type) > 1) {
									$str_processingnote_type .= ', ' . Wcms_ContentboxController::getContenbox($processing_type, $language_id);
								} else {
									$str_processingnote_type .= Wcms_ContentboxController::getContenbox($processing_type, $language_id);
								}
							}
							echo $str_processingnote_type;
		          ?>
					</h4>
				</div>
			</div>
			<?php
				$height = 137;
		
				if (count($serie["materialvorteile"]) > count($serie["anwendungsbereiche"])) {
					$height_add = count($serie["materialvorteile"]) * 26;
				} else {
					$height_add = count($serie["anwendungsbereiche"]) * 26;
				}
				$height = $height_add + $height;
			?>

			<!-- Anwendungsbereiche -->
			<div class="anwendungsbereiche paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-extralight dark-font col-sm-13 vertical-center_" style="height: <?php echo $height; ?>px;">
				<div style="background-image:url('<?php echo $website_url; ?>/sites/default/files/assets/pattern/extralight.png')" class="pattern-outer">
					<div class="smallspace-wrapper clearfix pattern-inner">
						<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
							<p class="copy-text-bold"><?php print Wcms_ContentboxController::getContenbox('pdb---typical-applications', $language_id); ?></p>
								<ul>
									<?php foreach ($serie["anwendungsbereiche"] as $anwendungsbereich) { ?>
										<li>
											<?php print trim(str_replace(array("<p>", "</p>", "<P>", "</P>"), array("", " "), $anwendungsbereich)); ?>
										</li>
									<?php } ?>
								</ul>
							<p>&nbsp;</p>
						</div>
					</div>
				</div>
			</div>
			<!-- MATERIALVORTEILE -->
			<div class="materialvorteile paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-blue light-font col-sm-11" style="height: <?php echo $height; ?>px;">
				<div style="background-image:url('<?php echo $website_url; ?>/sites/default/files/assets/pattern/blue.png')" class="pattern-outer">
					<div class="smallspace-wrapper clearfix pattern-inner">
						<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
							<p class="copy-text-bold"><?php print Wcms_ContentboxController::getContenbox('pdb---material-advantages', $language_id); ?></p>
							<ul>
								<?php foreach ($serie["materialvorteile"] as $materialvorteile) { ?>
									<?php //if (true === empty($materialvorteile)) { continue; } ?>
									<li>
										<?php print trim(str_replace(array("<p>", "</p>", "<P>", "</P>"), array("", " "), $materialvorteile)); ?>
									</li>
								<?php } ?>
							</ul>
							<p>&nbsp;</p>
						</div>
					</div>
				</div>
			</div>
			
<?php include_once ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'elements' . DS . 'datasheetseries.phtml'; ?>
			
<?php include_once ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'elements' . DS . 'sdsseries.phtml'; ?>
			
    	<div class="row ct-u-padding-bottom-80">

        <!--
				<div class="col-sm-6 pdb-series-description">
        	<h3>
	        	<?php if ($language_id == 8 || $language_id == 5 || $language_id == 11 || $language_id == 4) { ?> 
	        	<?php print Wcms_ContentboxController::getContenbox('pdb---series', $language_id) . ' ' . $serie["name"]; ?>
	        	<?php } else { ?>
	        	<?php print $serie["name"] . ' ' .  Wcms_ContentboxController::getContenbox('pdb---series', $language_id); ?>
	        	<?php } ?>
        	</h3>
        	<div class="row">
        		<div class="col-sm-12">
	        	<?php
	              if ($type == "serie") {
	                  print trim(str_replace(array("<p>", "</p>", "<P>", "</P>"), array("", " "), $serie["description"]));
	              } else {
	                  print trim(str_replace(array("<p>", "</p>", "<P>", "</P>"), array("", " "), $serie["text1"]));
	              }
	          ?>
            </div>
          </div>
          <div class="row">
          	<div class="col-sm-12">
		          <?php
		            $processingnote_types = array();
		            foreach ($processingnotes as $processingnote_type => $processingnote) {
		                $processingnote_types[] = trim(str_replace(array("<p>", "</p>", "<P>", "</P>"), array("", " "), $processingnote_type));
		            }
		            print implode(", ", $processingnote_types);
		          ?>
            </div>
          </div>
						
          <div class="row ct-u-padding-top-20">	
          	<div class="col-sm-12 pdb-material-description">
							<div id="1" role="tablist" aria-multiselectable="true" class="panel-group">
							               
							  <div class="panel panel-default">
							    <div role="tab" id="header-1" class="panel-heading">
							      <h4 class="panel-title"><a aria-controls="collapse-1" aria-expanded="false" data-parent="#1" data-toggle="collapse" href="#collapse-1" role="button">
											<?php print Wcms_ContentboxController::getContenbox('pdb---typical-applications', $language_id); ?>
											</a></h4>
							    </div>
							    <div id="collapse-1" role="tabpanel" aria-labelledby="header-1" class="panel-collapse collapse in">
							      <div class="panel-body">
							      	<ul>
							    		<?php foreach ($serie["anwendungsbereiche"] as $anwendungsbereich) { ?>
								        <?php //if (true === empty($anwendungsbereich)) { continue; } ?>
								        <li class="col-sm-6">
								        	<?php print trim(str_replace(array("<p>", "</p>", "<P>", "</P>"), array("", " "), $anwendungsbereich)); ?>
								        </li>
								      <?php } ?>
								      </ul>
							      </div>
							    </div>
							  </div>
							                
							  <div class="panel panel-default">
							    <div role="tab" id="header-2" class="panel-heading">
							      <h4 class="panel-title"><a aria-controls="collapse-2" aria-expanded="false" data-parent="#1" data-toggle="collapse" href="#collapse-2" role="button">
											<?php print Wcms_ContentboxController::getContenbox('pdb---material-advantages', $language_id); ?>
											</a></h4>
							    </div>
							    <div id="collapse-2" role="tabpanel" aria-labelledby="header-2" class="panel-collapse collapse">
							      <div class="panel-body">
							      	<ul>
							        <?php foreach ($serie["materialvorteile"] as $materialvorteile) { ?>
							            <?php //if (true === empty($materialvorteile)) { continue; } ?>
							            <li class="col-sm-6">
							            	<?php print trim(str_replace(array("<p>", "</p>", "<P>", "</P>"), array("", " "), $materialvorteile)); ?>
							            </li>
							        <?php } ?>
							        </ul>
							      </div>
							    </div>
							  </div>
							</div>        		
           </div>
         </div>





      </div>-->
				
				

				
				
      <div class="col-sm-24 ct-u-padding-top-30 cts-u-padding-bottom-20 tpe-downloadcenter">
      	  <div class="row">

						
						
          <!--
          <div class="row">
						<div class="col-sm-24">
						  <?php 
						  		$path_include = ASSETS . DS . "tpepdb2" . DS . "templates" . DS . "elements" . DS . "downloadcenter.phtml";
						  		//$path_include = ASSETS . DS . "tpepdb2" . DS . "templates" . DS . "elements" . DS . "datacenter.phtml";
						  		//echo $path_include;
						   		include_once $path_include; 
						  ?>
						</div>
          </div>-->
          
			  </div>
      	
      	

  		</div>
	  </div>
  </div>
</section>

<?php } ?>