<?php
if (Ncw_Configure::read('developer_internal_ip') != $_SERVER['REMOTE_ADDR'] ) {
	//echo Ncw_Configure::read('developer_internal_ip');
	//exit;
} 

$arr_headline = $this->getSerieHeadline($serie, $language_id );
$arr_compounds = $this->getSerieValues($serie, $language_id );


$color1_header = '#075399';
$color2_header = '#66676e';

$arr_note = $arr_notecount = array();
$notecount = 0;

$columns_list = array();
$columns = array();

$column_count = 0;
$width = 0;

// Prüfen ob es ein Compound mit Recyclinganteil gibt
$recycling = false;
foreach ($arr_compounds As $compound) {
    if ($compound[0]["compound_recyclinganteil"] > 0) {
        $recycling = true;
    }
}
// Prüfen ob es ein Compound mit Bioanteil gibt
$biological = false;
foreach ($arr_compounds As $compound) {
    if ($compound[0]["compound_bioanteil"] > 0) {
        $biological = true;
    }
}

if (count($arr_compounds) > 0) {
    $note_texts = array();
	$flag_first = false;
    
	foreach ($compounds as $compound) {
		$pos = 1;
		$columns[0] = array('<b>' . Wcms_ContentboxController::getContenbox('pdb---datasheet---compound-name', $language_id) . '</b><br /><br >');
		$columns[1] = array('<b>' . Wcms_ContentboxController::getContenbox('pdb---datasheet---srs-color', $language_id) . '</b><br /><br >');
		// $arr_str_footer ist für die Fußnoten notwendig
		if ($flag_first == false) {
			$arr_str_footer = array();
			$count_sup = 1;
			$label_sup = '';
		}

		foreach ($arr_headline as $value) {
			
			$label_sup = '';
			if (strlen($value['footer']) > 1) {
				if (false == in_array(trim($value['footer']), $arr_str_footer)) {
					$arr_str_footer[$count_sup] = trim($value['footer']);
					$label_sup = '<sup> ' . $count_sup . '</sup>';
					$count_sup++;
				} else {
					$label_sup = '<sup>' . array_search ( trim($value['footer']) , $arr_str_footer ) . '</sup>';
					//$label_sup = '1';
				}
			}
			
			$pos++;
			$value['einheit'] = trim(str_replace('Ω', '<img src="/assets/files/uploads/ohmw.png" style="border: 0; height: 13px;">', $value['einheit']));
			$value['einheit'] = str_replace('GOhm', 'Ohm', $value['einheit']);
			$value['name'] = trim(str_replace('Ω', '<img src="/assets/files/uploads/ohm.png" style="border: 0; height: 13px;">', $value['name']));
			$value['norm'] = trim(str_replace('Ω', '<img src="/assets/files/uploads/ohm.png" style="border: 0; height: 13px;">', $value['norm']));
			$label_sup = trim(str_replace('Ω', '<img src="/assets/files/uploads/ohm.png" style="border: 0; height: 13px;">', $label_sup));

			$column_name = '<b>' . $value['name'] . $label_sup . '</b><br />' . $value['norm'] . '<br />' . $value['einheit'];
			$columns[$pos] = array($column_name);
		}
		// Zusätzliche Spalte Recycling wenn vorhanden
		if ($recycling == true) {
			$recyclingString = '<b>' .Wcms_ContentboxController::getContenbox('rawmaterials', $language_id) . '</b><br />%';
			$columns[$pos+1] = array($recyclingString);
		}
		// Zusätzliche Spalte Bioanteil wenn vorhanden
		if ($biological == true) {
			$biologicalString = '<b>' .Wcms_ContentboxController::getContenbox('biologicalmaterials', $language_id) . '</b><br />%';
			$columns[$pos+1] = array($biologicalString);
		}
		$flag_first = true;
    }
	$name_width = 10;
	$color_width = 0;
	$plusCol = 1;
	if ($recycling == true) {
		$plusCol = 2;
	}
	if ($biological == true) {
		$plusCol = 2;
		if ($recycling == true) {
			$plusCol = 3;
		}
	}	
	$width = ((100 - $name_width) - $color_width) / ($column_count + $plusCol);
}
?>
<?php if (count($compounds) > 0) { ?>
    
<?php 
	$tr_serie_compounds_headline_cols = '';
	$pdf->pdf_mode = 'series';
	$name_width = 10;
	$color_width = 0;
	$width_td = ((100 - $name_width) - $color_width) / (count($arr_headline) + $plusCol);
?>

<tcpdf method="AddPage" />
    <table class="tpepdb2_rotate_table_content" width="100%" cellspacing="0" cellpadding="2" border="0" style="border: none;">
			<thead>
            <tr style="background-color: #ffffff; color: #134d93;">
                <th style="display: none; font-size: <?php echo $font_size_table; ?>;color:#134d93; background-color: #fff; height: 215px; width: 1px; display: none;"></th>
                <?php 
						$ct = 0;
						foreach ($columns as  $column) {
							if ($ct == 0) {
								$td_width_print = $name_width;
								$bg_color = $color2_header;
								$border_left = 0;
							} else {
								$td_width_print = $width_td;
								$bg_color = $color2_header;
								$border_left = 4;
							}
							$ct++;							
						?>
                    <th style="background-color: <?php echo $bg_color; ?>; font-size: <?php echo $font_size_table; ?>;border-left: <?php echo $border_left; ?>px solid #fff; color:#134d93; width:<?php echo $td_width_print; ?>%; height: 215px;">
                      <tcpdf data="<?php echo $pdf->serializeTCPDFtag('RotateCellContent', array()); ?>" />
					</th>
                <?php } ?>
            </tr>
        </thead>

        <tbody>
            <?php $count = 0;?>
            <?php $last_compound_first_letters = ""; ?>
            <?php $bg_color = ""; ?>
					
						<!-- Hier wird die Reihe der Compounds ausgegeben -->
					
					
					
            <?php 
								$ctcompound = 0;	
								foreach ($arr_compounds as $compound) { 
									if ($ctcompound > 15) {
										$pdf->setAutoPageBreak(true);
										echo '        </tbody>

    </table>';
										echo '<tcpdf method="AddPage" />';

										?>
									
									
    <table class="tpepdb2_rotate_table_content" width="100%" cellspacing="0" cellpadding="2" border="0" style="border: none;">
			<thead>
            <tr style="background-color: #ffffff; color: #134d93;">
                <th style="display: none; font-size: <?php echo $font_size_table; ?>;color:#134d93; background-color: #fff; height: 215px; width: 1px; display: none;"></th>
                <?php 
					$ct = 0;
					foreach ($columns as  $column) {
						if ($ct == 0) {
							$td_width_print = $name_width;
							$bg_color = $color2_header;
							$border_left = 0;
						} else {
							$td_width_print = $width_td;
							$bg_color = $color2_header;
							$border_left = 4;
						}
						$ct++;
					?>
                    <th style="background-color: <?php echo $bg_color; ?>; font-size: <?php echo $font_size_table; ?>;border-left: <?php echo $border_left; ?>px solid #fff; color:#134d93; width:<?php echo $td_width_print; ?>%; height: 215px;">
                      <!--<tcpdf method="RotateCellContent" params="<?php print $label_sup . $params; ?>" />-->
					</th>
                <?php } ?>

            </tr>
        </thead>
						
        <tbody><?php
						
					$ctcompound = 0;
					//break;
				}
					$ctcompound++;
				?>
                <?php
                $substr = substr($compound[0]['compound_name'] ?? '', 0, 3);
                
                    if (true == is_int($count / 2)) {
                        $bg_color = "#e3e3e3";
                    } else {
                        $bg_color = "#f1f1f1";
                    }
         
                ?>
                <tr nobr="true" style="height: 32px; background-color: <?php  print $bg_color; ?>;">
                   <td style="vertical-align: middle; height: 32px; border-bottom: 4px solid #fff; width: <?php if (true === $is_pdf) { print $name_width. "%"; } ?>;">
						<table style="width: 100%" cellpadding="0" cellspacing="0">
                            <tr><td style="height: 7px;font-size: 2px;line-height: 2px">&nbsp;</td></tr>
                            <tr><td style="font-size: <?php echo $font_size_table; ?>;text-align: center;"><?php if (false === $is_pdf) { ?><a href="?cid=<?php print ($compound["id"] ?? 0); ?><?php if ($language == "it") { ?>&amp;ls=it<?php } ?><?php if ($language == "pl") { ?>&amp;ls=pl<?php } ?>"><?php } ?><b><?php  print $compound[0]["compound_name"]; ?></b><?php if (false === $is_pdf) { ?></a><?php } ?></td></tr>
                        </table>
                    </td>
										
                    <td style="vertical-align: middle; border-bottom: 4px solid #fff;border-left: 4px solid #fff; width: <?php  print $width_td. "%"; ?>;">
						<table style="width: 100%" cellpadding="0" cellspacing="0">
                            <tr><td style="height: 7px;font-size: 2px;line-height: 2px">&nbsp;</td></tr>
                            <tr><td style="font-size: <?php echo $font_size_table; ?>;text-align: center;"><?php echo $this->getColorNameById($compound[0]['compound_id'], $language_id); ?></td></tr>
                        </table>
                    </td>
                    <?php foreach ($compound as $value) {
						$value['value'] = str_replace("<", "&lt;	", $value['value']);
						$value['value'] = str_replace(">", "&gt;	", $value['value']);
									 ?>
                        <td style="vertical-align: middle; border-bottom: 4px solid #fff;border-left: 4px solid #fff; width: <?php if (true === $is_pdf) { echo $width_td . "%"; } else { print $column[1] ."px"; } ?>;">
							<table style="width: 100%" cellpadding="0" cellspacing="0">
                                <tr><td style="height: 7px;font-size: 2px;line-height: 2px">&nbsp;</td></tr>
                                <tr><td style="font-size: <?php echo $font_size_table; ?>;text-align: center;"><?php print $value['value']; ?></td></tr>
                            </table>
                        </td>
                    <?php } ?>
					<?php  if ($recycling == true) { // Wenn ein Compound einen Recyclinganteil hat ?>
						<td style="vertical-align: middle; border-bottom: 4px solid #fff;border-left: 4px solid #fff; width: <?php  print $width_td. "%"; ?>;">
							<table style="width: 100%" cellpadding="0" cellspacing="0">
								<tr><td style="height: 7px;font-size: 2px;line-height: 2px">&nbsp;</td></tr>
								<tr><td style="font-size: <?php echo $font_size_table; ?>;text-align: center;"><?php echo round($compound[0]["compound_recyclinganteil"], 0); ?></td></tr>
							</table>
						</td>
					<?php } ?>
					<?php  if ($biological == true) { // Wenn ein Compound einen Bioanteil hat ?>
						<td style="vertical-align: middle; border-bottom: 4px solid #fff;border-left: 4px solid #fff; width: <?php  print $width_td. "%"; ?>;">
							<table style="width: 100%" cellpadding="0" cellspacing="0">
								<tr><td style="height: 7px;font-size: 2px;line-height: 2px">&nbsp;</td></tr>
								<tr><td style="font-size: <?php echo $font_size_table; ?>;text-align: center;"><?php echo round($compound[0]["compound_bioanteil"], 0); ?></td></tr>
							</table>
						</td>
					<?php } ?>
                </tr>
                <?php ++$count; ?>
            <?php } ?>

        </tbody>

    </table>
<?php } ?>
<?php  ?>
<?php
if (true === $is_pdf) {
    $pdf->writeHTML(ob_get_clean(), true, false, true, false, "");
    $pdf->table_end = $pdf->getPage();

}
?>

<?php ob_start(); ?>
<?php 
	include_once ASSETS . DS . "tpepdb2" . DS . "templates" . DS . "elements" . DS . "notes" . DS . "notes_print.phtml"; 
?>
<?php 
	include_once ASSETS . DS . "tpepdb2" . DS . "templates" . DS . "elements" . DS . "text.phtml"; 
?>
<br />



	
