<?php 
$url_pdb = Ncw_Configure::read('Project.url');
?>

<div class="paragraph clearfix panel-group paragraph--type--akkordeon paragraph--view-mode--default ct-u-padding-top-40" id="393" role="tablist" aria-multiselectable="true" style="">
		<div class="panel panel-default">
			<div class="panel-heading flaticon-leave-right dark-font" role="tab" id="headingOne">
				<h4 class="panel-title">
					<a role="button" data-toggle="collapse" data-parent="#390" href="#target393" aria-expanded="false" aria-controls="target393" class="noTrigger collapsed">
						
						<?php echo  Wcms_ContentboxController::getContenbox('pdb2-datasheet-to-download', $language_id); ?>

						<span class="kbtpe-icon-minus minus"></span>
						<span class="kbtpe-icon-plus plus"></span>
					</a>
				</h4>
			</div>
			<div id="target393" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
				<div class="panel-body">
					<div class="row">

						
						 <div class="rows  ncw-u-padding-bottom-20">
							<div class="cols-sm-12">
								<h5>
									<?php print Wcms_ContentboxController::getContenbox('please-choose-language-of-datasheet', $language_id); ?>
								</h5>
							</div>
						 </div>
						<!-- Auflistung aller Sprachen datasheetseries.php-->
						<?php 
						//array(11) { ["English"]=> string(2) "en" ["Deutsch"]=> string(2) "de" ["中文"]=> string(2) "zh" ["Español"]=> string(2) "es" ["Français"]=> string(2) "fr" ["Americas"]=> string(2) "us" ["日本語"]=> string(2) "jp" ["Italiano"]=> string(2) "it" ["Portuguese"]=> string(2) "pt" ["한국어"]=> string(2) "kr" ["Polski"]=> string(2) "pl" }
						//var_dump($languages);
						//array(8) { ["Deutsch"]=> string(2) "de" ["English"]=> string(2) "en" ["Español"]=> string(2) "es" ["Français"]=> string(2) "fr" ["日本語"]=> string(2) "jp" ["한국어"]=> string(2) "kr" ["Polski"]=> string(2) "pl" ["中文"]=> string(2) "zh" }
						
						$languages["English"] =  "en";
						$languages["Deutsch"] =  "de";
						$languages["中文"] =  "zh";
						$languages["Español"] =  "es";
						$languages["Français"] =  "fr";
						$languages["日本語"] =  "jp";
						$languages["한국어"] =  "kr";
						$languages["Polski"] =  "pl";	
						$languages["Italiano"] =  "it";
						foreach ($languages as $key => $value) { 
							if ($value != 'pt') {
							?>
								<div class="paragraph clearfix paragraph--type--download paragraph--view-mode--default color-scheme-darkgrey light-font col-md-8 col-sm-12 no_image" style="height: 57px;">
									<div class="clearfix">
												<div class="col-xs-18 download-info" style="background-image:url('<?php echo $website_url; ?>/sites/default/files/assets/pattern/dark-grey.png')">

											<div class="icon kbtpe-icon-download">
												 <span class="download-datum"> PDF file - 1MB</span><span class="download-title"><?php print $key; ?></span>
											</div>
											<?php if (true == TpePdbWeb::rights()) { ?>
												<!--<a href="javascript: open_share_dialog('datasheet', '<?php echo $value; ?>', '<?php echo $id; ?>', '<?php echo $url_pdb; ?>/tpepdb/pdf?sid=<?php echo $id; ?>&amp;l=<?php echo $value; ?>', 'series');" target="_blank" class="share-buton">-->
													<div class="icosn kbtpe-icon-share" onclick="open_share_dialog('datasheet', '<?php echo $value; ?>', '<?php echo $id; ?>', '<?php echo $url_pdb; ?>/tpepdb/pdf?sid=<?php echo $id; ?>&amp;l=<?php echo $value; ?>', 'series');"></div>
												<!--</a>-->
											<?php } ?>
										</div>
									</div>
									<a href="<?php echo $url_pdb; ?>/tpepdb/pdf?sid=<?php echo $id; ?>&amp;l=<?php echo $value; ?>&amp;datasheetmode=datasheet" target="_blank" class="clickhelper" onclick="tpepedb2stats('<?php echo $url_pdb; ?>/tpepdb/pdf?sid=<?php echo $id; ?>','<?php echo $value; ?>', 'series', 'datasheet', 'download');"><span class="hidden">Download</span></a>
								</div>
								<?php } // Ende nicht PT ?>
						  <?php } ?>
						<div class="panel-space"></div>
					</div>
				</div>
			</div>
		</div>
	</div>

		<?php include_once ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'elements' . DS . 'share_dialog.phtml'; ?>