<!--[if lt IE 8]>
<style>
    .back_to_search {
        top: 2px !important;
        height: 28px !important;
    }
</style>
<![endif]-->
<?php
$sds_lang_name = array("us" => "English");
foreach ($languages as $sds_lang_item => $sds_lang_key) {
    $sds_lang_name[$sds_lang_key] = $sds_lang_item;
}
?>

<?php 
$str_compoundname_for_url = '';
if (true == isset($compound["name"])) {
	$str_compoundname_for_url = str_replace('-', '_', $compound["name"]); 
}
?>

<div id="data_header">
    <?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---data-center', $language_id); ?>
    <div class="back_to_search">
        <a href="?sess=1<?php if ($language == 'it') { ?> &amp;ls=it <?php } ?><?php if ($language == 'pl') { ?>&amp;ls=pl<?php } ?>"><img src="<?php print Ncw_Configure::read('Project.url'); ?>/assets/wcms/files/tpepdb2_back_arrow.jpg" /></a>
        <a href="?sess=1<?php if ($language == 'it') { ?> &amp;ls=it <?php } ?><?php if ($language == 'pl') { ?>&amp;ls=pl<?php } ?>"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---back-to-search', $language_id); ?></a>
    </div>
</div>
<div class="tpepdb2_languages_select_bg" style="z-index: 999; position: absolute; top: 0; left: 0; height: 100%; width: 100%; background-color: transparent; display: none;">&nbsp;</div>
<div id="data_content">
    <p>
        <?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---data-center-info', $language_id); ?>
    </p>
    <div class="data_content">
        <div class="data_content_left">
            <label><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---download-datasheet', $language_id); ?></label><br />
            <input id="tpepdb2_type" type="hidden" value="<?php print $url_type; ?>" />
            <input id="tpepdb2_id" type="hidden" value="<?php print $id; ?>" />
            <input id="language" type="hidden" value="<?php print $language_id; ?>" />
            <input id="tpepdb2_languages_select" type="hidden" value="<?php print $language; ?>" />
            <div value="<?php print $language; ?>" style="position: relative; width: 190px; height: 19px; margin: 14px 0 4px 0; padding: 5px 0px 0px 8px; border: 1px solid #ccc; background-color: #fff;">
                <?php if (count($languages) > 1) { ?>
                    <div class="tpepdb2_languages_select_arrow" style="z-index: 1000; position: absolute; right: 0; top: 0; height: 22px; width: 22px; background-color: #ddd; border: 1px solid #fff;z-index: 1001;">
                        <img style="margin:0" src="<?php print Ncw_Configure::read('Project.url'); ?>/assets/wcms/files/tpepdb2_language_select.jpg" />
                    </div>
                <?php } ?>
                <?php $y = 24; ?>
                <?php foreach ($languages as $key => $value) { ?>
                    <?php
                    $img = $value;
                    if ($img == "en") {
                        $img = "en_us";
                    }
                    ?>
                    <div class="<?php if ($value != $language) { ?>tpepdb2_languages_select_option<?php } else { ?>tpepdb2_languages_select_option_selected<?php } ?>" style="z-index: 1000; cursor: pointer; position: absolute; width: 190px; height: 19px; padding: 5px 0px 0px 8px; border: 1px solid #ccc; background-color: #fff; <?php if ($value != $language) { ?>left: -1px; top: <?php print $y; ?>px; display: none;<?php } else { ?>top: -1px; left: -1px;<?php } ?>" value="<?php print $value; ?>">
                        <img style="margin-top:0px;" src="<?php print Ncw_Configure::read('Project.url'); ?>/themes/default/web/images/country_flags/<?php print $img; ?>.gif" alt="<?php print $key; ?>" title="<?php print $key; ?>" />
                        <?php print $key; ?>
                    </div>
                    <?php if ($value != $language) { $y += 24; } ?>
                <?php } ?>
            </div>
            <a href="<?php print Ncw_Configure::read('Project.url') . "/tpepdb/pdf" . "?" . $url_type . "=" . $id . "&l=" . $language; ?>" target="_blank" class="tpepdb2_download"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="" title="" /></a>
            <a href="<?php print Ncw_Configure::read('Project.url') . "/tpepdb/pdf" . "?" . $url_type . "=" . $id . "&l=" . $language; ?>" target="_blank" class="tpepdb2_download">
                <?php
                if ($type == "serie" || $compound['status'] == 'portfolio') {
                    print Wcms_ContentboxController::getContenbox('pdb---datasheet---download-datasheet', $language_id);
                } else {
                    //print Wcms_ContentboxController::getContenbox('pdb---datasheet---download-test-report', $language_id);
                    print Wcms_ContentboxController::getContenbox('pdb---datasheet---download-datasheet', $language_id);
                }
                ?>
            </a>
        </div>
        <div class="data_content_right">
            <?php
            $doc_num = 0;
            foreach ($documents as $document) {
                if ($document['type'] == 'CRD') {
                    ++$doc_num;
                }
            }
            ?>
            <?php
            if ($type == "compound" && $compound["safetydata"] != "") {
                ++$doc_num;
            }
            ?>
            <?php if ($doc_num > 0) { ?>
                <label><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---download-related-docs', $language_id); ?></label><br />
                <table style="width:100%">
                    <?php $docs_count = 0; ?>

                    <?php if ($type == "compound" && $compound["safetydata"] != "") { ?>
                         <tr>
                        <?php
                        $set_region = 0;

                        if (Ncw_Components_Session::checkInAll("tpepdb2_last_search")) {
                            $last_search = Ncw_Components_Session::readInAll("tpepdb2_last_search");
                            $set_region = $last_search["region_id"];
                        }

                        if ($set_region == 0) {
                            $not_logged_in = false;
                        } else {
                            $not_logged_in = true;
                        }

                        if ($not_logged_in == false && $compound['status'] == 'portfolio') {
                            if ($_SERVER['REMOTE_ADDR'] != '9984.145.28.245') {
                                //var_dump($serie["regions"]);
                                $serie["regions"] = array('region_id' => 1);
                                $serie["regions"][] = array('region_id' => 2);
                                $serie["regions"][] = array('region_id' => 3);
                                
                            }
                        }
                         
                        foreach ($serie["regions"] as $region) {

                            if (true === $not_logged_in && $set_region != 0 && $region["region_id"] != $set_region) {
                                continue;
                            }

                           if (true === isset($language_us) && true === $language_us) {
                                $sds_language = "us";
                            } else {
                                $sds_language = $language;
                            }

                            $region_name = "";
                            //if ($set_region == 0) {
                                switch ($region["region_id"]) {
                                    case 1:
                                        $region_name = explode(" ", str_replace(array("，"), " ", Wcms_ContentboxController::getContenbox('pdb---search---region---emea', $language_id)));
                                        $region_name = " " . str_replace(array(","), "", $region_name[0]) . "";
                                        $set_region = 1;
                                        break;
                                    case 2:
                                        $region_name = explode(" ", str_replace(array("，"), " ", Wcms_ContentboxController::getContenbox('pdb---search---region---americas', $language_id)));
                                        $region_name = " " . str_replace(array(","), "", $region_name[0]) . "";
                                        $sds_language = "us";
                                        $set_region = 2;
                                        break;
                                    case 3:
                                        $region_name = explode(" ", str_replace(array("，"), " ", Wcms_ContentboxController::getContenbox('pdb---search---region---asia-pacific', $language_id)));
                                        $region_name = " " . str_replace(array(","), "", $region_name[0]) . "";
                                        $set_region = 3;
                                        break;
                                }
                            //}

                            if (false == in_array($sds_language, array('de', 'fr', 'it', 'pl', 'es')) && $set_region == 1) {
                                $sds_language = "en";
                            }
                            if (false == in_array($sds_language, array('us')) && $set_region == 2) {
                                $sds_language = "us";
                            }
                            if (false == in_array($sds_language, array('zh', 'jp', 'kr')) && $set_region == 3) {
                                $sds_language = "en";
                            }

                            $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_" . $sds_language . ".pdf";
                            //if (true === is_file($sds_path)) {
                                $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=" . $compound["safetydata"] . "&l=" . $sds_language . "&t=" . $str_compoundname_for_url . "&r=" . $region["region_id"];
                            ?>
                            <?php if ($docs_count % 2 == 0) { ?>
                                <?php if ($docs_count > 0) { ?></tr><?php } ?>
                                <tr>
                            <?php } ?>
                                <td style="width: 47.5%" class="compound_document <?php if ($doc_num > 2 && $docs_count >= 2) { ?>document_border<?php } ?>">
                                    <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?>" title="<?php print $compound["safetydata"]; ?>" /></a>
                                    <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . $region_name . ' (' . $sds_lang_name[$sds_language] . ')'; ?></a>
                                </td>
                                <td style="width: 5%;">&nbsp;</td>
                            <?php
                                $docs_count++;

                                if (true == in_array($sds_language, array('de', 'fr', 'it', 'pl', 'es')) && $set_region == 1) {
                                    $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_en.pdf";
                                    $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=" . $compound["safetydata"] . "&l=en&t=" . $str_compoundname_for_url . "&r=" . 1;
                                ?>
                                    <td style="width: 47.5%" class="compound_document <?php if ($doc_num > 2 && $docs_count >= 2) { ?>document_border<?php } ?>">
                                        <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> EN" title="<?php print $compound["safetydata"]; ?> EN" /></a>
                                        <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . $region_name . ' (' . $sds_lang_name['en'] . ')'; ?></a>
                                    </td>
                                    <td style="width: 5%;">&nbsp;</td>
                                    <?php $docs_count++; ?>
                                    <?php if ($docs_count % 2 == 0) { ?>
                                        <?php if ($docs_count > 0) { ?></tr><?php } ?>
                                        <tr>
                                    <?php } ?>
                                <? } else if (true === $not_logged_in && false == in_array($sds_language, array('zh', 'kr', 'jp')) && $set_region == 3) {
                                        // ZH
                                        if ($compound["safetydata"] != 'S4 HIPEX') {
                                            $asia_sds = array("zh", "kr", "jp");
                                            foreach ($asia_sds as $asia_sds_item) {
                                                $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_" . $asia_sds_item . ".pdf";
                                                $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=" . $compound["safetydata"] . "&l=" . $asia_sds_item . "&t=" . $str_compoundname_for_url . "&r=" . 3;
                                        ?>

                                                <td style="width: 47.5%" class="compound_document <?php if ($doc_num > 2 && $docs_count >= 2) { ?>document_border<?php } ?>">
                                                    <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> <?php print strtoupper($asia_sds_item); ?>" title="<?php print $compound["safetydata"]; ?> <?php print strtoupper($asia_sds_item); ?>" /></a>
                                                    <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . $region_name . ' (' . strtoupper($sds_lang_name[$asia_sds_item]) . ')'; ?></a>
                                                </td>
                                                <td style="width: 5%;">&nbsp;</td>
                                                <?php $docs_count++; ?>
                                                <?php if ($docs_count % 2 == 0) { ?>
                                                    <?php if ($docs_count > 0) { ?></tr><?php } ?>
                                                    <tr>
                                                <?php } ?>
                                        <?php
                                            }
                                        }

                                } else if (true == in_array($sds_language, array('zh', 'kr', 'jp')) && $set_region == 3) { // wenn region 3 und ZH als Sprache zusätzlich ASIA
                                        // ZH
                                        if ($compound["safetydata"] != 'S4 HIPEX') {
                                            $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_asia.pdf";
                                            $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=" . $compound["safetydata"] . "&l=en&t=" . $str_compoundname_for_url . "&r=" . 3;
                                            ?>

                                            <td style="width: 47.5%" class="compound_document <?php if ($doc_num > 2 && $docs_count >= 2) { ?>document_border<?php } ?>">
                                                <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> EN" title="<?php print $compound["safetydata"]; ?> EN" /></a>
                                                <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . $region_name . ' (' . $sds_lang_name['en'] . ')'; ?></a>
                                            </td>
                                            <td style="width: 5%;">&nbsp;</td>
                                            </tr>
                                            <tr>
                                        <?php }
                                        $docs_count++;
                                }
                            //}
                        }

                        // NONPORTFOLIO // Umgebaut am 15.10.2014 winni
                        if ($compound["status"] == "non_portfolio") {
                            $sds_lang = array("en", "us", "de", "asia", "fr", "zh", "it", "kr",  "es", "jp", "pl");

                            // Diese Ausnahme wurde am 07.04.2016 auf Wunsch von TPE eingeführt. Für das eine Compound gibt es nur diese
                            // Sprachen
                            if ($compound["name"] == 'HX6ICN') {
                                $sds_lang = array("en", "us", "de", "asia", "zh", "kr", "jp");
                            }
                            // Diese Ausnahme wurde am 19.04.2016 auf Wunsch von TPE eingeführt. Für das eine Compound gibt es nur de und en
                            // Sprachen
                            if ($compound["name"] == 'HTF8675/69') {
                                $sds_lang = array("de", "en");
                            }
                            
                            foreach ($sds_lang as $sds_item) {
                                $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_" . $sds_item . ".pdf";
                                $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=" . $compound["safetydata"] . "&l=" . $sds_item . "&t=" . $str_compoundname_for_url;

                                $str_region = ' EMEA ';
                                $str_language_addon = '';
                                if ($sds_item == 'us') {
                                	$str_region = ' Americas ';
                                }

                                if ($sds_item == 'asia' || $sds_item == 'zh' || $sds_item == 'kr'  || $sds_item == 'jp') {
                                	$str_region = ' Asia ';
                                }

                                if ($sds_item == 'asia') {
                                	$str_language_addon = 'English';
                                }
                                ?>

                                <td style="width: 47.5%" class="compound_documents <?php if ($doc_num > 2 && $docs_count >= 2) { ?>document_border<?php } ?>">
                                    <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> <?php print strtoupper($sds_item); ?>" title="<?php print $compound["safetydata"]; ?> <?php print strtoupper($sds_item); ?>" /></a>
                                    <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . $str_region . ' (' . $sds_lang_name[$sds_item] . $str_language_addon . ')'; ?></a>
                                </td>
                                <td style="width: 5%;">&nbsp;</td>
                                <?php $docs_count++; ?>
                                <?php if ($docs_count % 2 == 0) { ?>
                                    <?php if ($docs_count > 0) { ?></tr><?php } ?>
                                    <tr>
                                <?php } ?>
                        <?php }

                            /*$sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_us.pdf";
                            $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=" . $compound["safetydata"] . "&l=us&t=" . $str_compoundname_for_url . "&r=" . 2;
                        ?>
                            <tr>
                            <td style="width: 47.5%" class="compound_document <?php if ($doc_num > 2 && $docs_count >= 2) { ?>document_border<?php } ?>">
                                <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> Americas" title="<?php print $compound["safetydata"]; ?> Americas" /></a>
                                <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . ' Americas'; ?></a>
                            </td>
                            <td style="width: 5%;">&nbsp;</td>

                            <?php
                            $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_en.pdf";
                            $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=" . $compound["safetydata"] . "&l=en&t=" . $str_compoundname_for_url . "&r=" . 1;
                            ?>
                            <td style="width: 47.5%" class="compound_document <?php if ($doc_num > 2 && $docs_count >= 2) { ?>document_border<?php } ?>">
                                <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> English" title="<?php print $compound["safetydata"]; ?> EMEA English" /></a>
                                <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . ' EMEA English'; ?></a>
                            </td>
                            <td style="width: 5%;">&nbsp;</td>
                            </tr>
                             <tr>

                            <?php if ($language == "de") {
                                $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_de.pdf";
                                $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=". $compound["safetydata"] . "&l=de&t=" . $str_compoundname_for_url . "&r=" . 1;
                            ?>
                                <td style="width: 47.5%" class="compound_document document_border">
                                    <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> German" title="<?php print $compound["safetydata"]; ?> EMEA German" /></a>
                                    <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . ' EMEA German'; ?></a>
                                </td>
                                <td style="width: 5%;">&nbsp;</td>
                            <?php } else if ($language == "it") {
                                $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_it.pdf";
                                $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=". $compound["safetydata"] . "&l=it&t=" . $str_compoundname_for_url . "&r=" . 1;
                            ?>
                                <td style="width: 47.5%" class="compound_document document_border">
                                    <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> German" title="<?php print $compound["safetydata"]; ?> EMEA Italian" /></a>
                                    <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . ' EMEA Italian'; ?></a>
                                </td>
                                <td style="width: 5%;">&nbsp;</td>
                            <?php } else if ($language == "fr") {
                                $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_fr.pdf";
                                $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=". $compound["safetydata"] . "&l=fr&t=" . $str_compoundname_for_url . "&r=" . 1;
                            ?>
                                <td style="width: 47.5%" class="compound_document document_border">
                                    <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> German" title="<?php print $compound["safetydata"]; ?> EMEA French" /></a>
                                    <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . ' EMEA French'; ?></a>
                                </td>
                                <td style="width: 5%;">&nbsp;</td>
                            <?php } else if ($language == "es") {
                                $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_es.pdf";
                                $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=". $compound["safetydata"] . "&l=es&t=" . $str_compoundname_for_url . "&r=" . 1;
                            ?>
                                <td style="width: 47.5%" class="compound_document document_border">
                                    <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> German" title="<?php print $compound["safetydata"]; ?> EMEA Spanish" /></a>
                                    <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . ' EMEA Spanish'; ?></a>
                                </td>
                                <td style="width: 5%;">&nbsp;</td>
                            <?php } ?>

                            <?php
                            // ZH
                            if ($compound["safetydata"] != 'S4 HIPEX' && $compound["safetydata"] != 'S3 For-Tec E' && $compound["safetydata"] != 'S2 COPEC') {
                                $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_zh.pdf";
                                $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=" . $compound["safetydata"] . "&l=zh&t=" . $str_compoundname_for_url . "&r=" . 3;
                            ?>
                                <td style="width: 47.5%" class="compound_document document_border">
                                    <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> Asia Pacific Chinese" title="<?php print $compound["safetydata"]; ?> Asia Pacific Chinese" /></a>
                                    <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . ' Asia Pacific Chinese'; ?></a>
                                </td>
                                <td style="width: 5%;">&nbsp;</td>
                                </tr>
                                <tr>
                            <?php }
                            // Asia
                            if ($compound["safetydata"] != 'S4 HIPEX') {
                                $sds_path = ASSETS . DS . "tpepdb2" . DS ."safetydata" . DS . $compound["safetydata"] . "_asia.pdf";
                                $sds_path = Ncw_Configure::read('Project.url') . "/tpepdb/safetydata?s=" . $compound["safetydata"] . "&l=en&t=" . $str_compoundname_for_url . "&r=" . 3;
                                ?>
                                <td style="width: 47.5%" class="compound_document document_border">
                                    <a href="<?php print $sds_path; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $compound["safetydata"]; ?> Asia Pacific English" title="<?php print $compound["safetydata"]; ?> Asia Pacific English" /></a>
                                    <a href="<?php print $sds_path; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---safety-data-sheet', $language_id) . ' Asia Pacific English'; ?></a>
                                </td>
                                <td style="width: 5%;">&nbsp;</td>
                                </tr>
                           <?php } */?>
                        <?php } ?>
                    <?php } ?>

                    <?php foreach ($documents as $document) { ?>
                        <?php if ($document['type'] == 'CRD') { ?>
                            <?php
                            $doc_name = explode("_", $document["name"]);
                            if ($type == "compound") {
                                $doc_name = strtoupper($doc_name[3]);
                            } else {
                                $doc_name = strtoupper($doc_name[2]);
                            }

                            if ($doc_name == "DER") {
                                $doc_name = "CSTB Homologation";
                            }
                            
													  $arr_cstb_names = array(
													  	'CSTB-HOMOLOGATION-2014',
													  	'TP7HPN',
													  	'TP7HPG',
													  	'TP7SKZ',
													  	'TP6HPN',
													  	'TP6HPG',
													  	'TP6SKZ',
													  	'TA7AOZ',
													  	'TC6EXN',
													  	'TC6EXN-701',
													  	'TC6EXN-999'
													  );
													  
                            if (true == in_array($doc_name, $arr_cstb_names)) {
                                $doc_name = "CSTB Homologation";
                            }
														
														// Lösung für ein Bezecinungsproblem eingebaut am 19.09.2017
                            if (true == strstr($document["path"], 'TPE_UL94-YellowCard_FR1')) {
                            	$doc_name = 'UL94-YellowCard_FR1';
                            }
                            if (true == strstr($document["path"], 'TPE_UL94-YellowCard_FR2')) {
                            	$doc_name = 'UL94-YellowCard_FR2';
                            }
                            if (true == strstr($document["path"], 'TPE_UL94-YellowCard_FRAD1')) {
                            	$doc_name = 'UL94-YellowCard_FRAD1';
                            }
                            ?>
                            <?php if ($docs_count % 2 == 0) { ?>
                                <?php if ($docs_count > 0) { ?></tr><?php } ?>
                                <tr>
                            <?php } ?>
                                <td style="width: 47.5%;" class="compound_document <?php if ($doc_num > 2 && $docs_count >= 2) { ?>document_border<?php } ?>">
                                    <a href="<?php print $document["path"]; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $document["name"]; ?>" title="<?php print $document["name"]; ?>" /></a>
                                    <a href="<?php print $document["path"]; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---download', $language_id) . ' ' . $doc_name; ?></a>
                                </td>
                                <?php if ($docs_count % 2 == 0) { ?>
                                   <td style="width: 5%;">&nbsp;</td>
                                <?php } ?>
                            <?php $docs_count++; ?>
                        <?php } ?>
                    <?php } ?>

                    <?php if ($type == "compound") { ?>
                        <?php foreach ($serie["documents"] as $document) { ?>
                            <?php if ($document['type'] == 'CRD') { ?>
                                <?php
                                $doc_name = explode("_", $document["name"]);
                                $doc_name = strtoupper($doc_name[2]);
                                if ($doc_name == "DER") {
                                    $doc_name = "CSTB Homologation";
                                }
																// Lösung für ein Bezecinungsproblem eingebaut am 19.09.2017
		                            if (true == strstr($document["path"], 'TPE_UL94-YellowCard_FR1')) {
		                            	$doc_name = 'UL94-YellowCard_FR1';
		                            }
				                        if (true == strstr($document["path"], 'TPE_UL94-YellowCard_FR2')) {
				                        	$doc_name = 'UL94-YellowCard_FR2';
				                        }
		                            if (true == strstr($document["path"], 'TPE_UL94-YellowCard_FRAD1')) {
		                            	$doc_name = 'UL94-YellowCard_FRAD1';
		                            }
                                ?>
                                <?php if ($docs_count % 2 == 0) { ?>
                                    <?php if ($docs_count > 0) { ?></tr><?php } ?>
                                    <tr>
                                <?php } ?>
                                    <td style="width: 47.5%;" class="compound_document <?php if ($doc_num > 2 && $docs_count >= 2) { ?>document_border<?php } ?>">
                                        <a href="<?php print $document["path"]; ?>" target="_blank"><img src="../../assets/wcms/files/pfd_pic.jpg" alt="<?php print $document["name"]; ?>" title="<?php print $document["name"]; ?>" /></a>
                                        <a href="<?php print $document["path"]; ?>" target="_blank"><?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---download', $language_id) . ' ' . $doc_name; ?></a>
                                    </td>
                                    <?php if ($docs_count % 2 == 0) { ?>
                                       <td style="width: 5%;">&nbsp;</td>
                                    <?php } ?>
                                <?php $docs_count++; ?>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>

                </table>
            <?php } ?>
        </div>
        <div style="clear:both"></div>
    </div>
</div>

