<?php if (true === $is_pdf) { ?>



<?php
} else {  // Ende PDF Anfang HTML
?>
<?php

	// $pdb_url = 'https://testsystem.kraiburg-tpe.com';
	$pdb_url = Ncw_Configure::read('Project.url');
	$website_url = 'https://www.kraiburg-tpe.com';

	include_once ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'elements' . DS . 'userstate.phtml';

	if (strlen($serie['description']) > 10) {
		$text_grauer_kasten_pdf = $serie['description'];
	} else {
		$text_grauer_kasten_pdf = $this->getSerieDescription($serie['id'], $language_id);
	}

?>

<div style="background-image:url('<?php echo $website_url; ?>/sites/default/files/assets/pattern/transparent.png')" class="paragraph clearfix paragraph--type--section paragraph--view-mode--default row section-bottom-space-big color-scheme-transparent">
	<div class="paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-blue light-font col-md-8" style="height: 141px;">
		<div style="background-image:url('<?php echo $website_url; ?>/sites/default/files/assets/pattern/blue.png')" class="pattern-outer">
			<div class="smallspace-wrapper clearfix pattern-inner">
				<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
					<h1 class="headline-1">
							<?php if ($language_id == 8 || $language_id == 5 || $language_id == 11 || $language_id == 4) { ?> 
									<?php print Wcms_ContentboxController::getContenbox('pdb---series', $language_id) . ' ' . $serie['name']; ?>
								<?php } else { ?>
									<?php print $serie['name'] . ' ' . Wcms_ContentboxController::getContenbox('pdb---series', $language_id); ?>
							<?php } ?>
					</h1>
					<h4 class="subheadline">
							<?php
							$serie_link = '?sid=' . $serie['id'];
							if ($language == 'it') {
								$serie_link .= '&amp;ls=it';
							}
							if ($language == 'pl') {
								$serie_link .= '&amp;ls=pl';
							}
							?>
						<?php
						if ($language_id != 3 || strlen($brand['name_zh']) < 1) {  // 3 ist Chinesisch und soll den eintrag name_zh benutezn
							print str_replace('®', '<sup>®</sup>', $brand['name']);
						} else {
							print str_replace('®', '<sup>®</sup>', $brand['name_zh']);
						}
						?>
						
						
						
						
					</h4>
				</div>
			</div>
		</div>
	</div>
	<div class="paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-extralight dark-font col-md-16" style="height: 141px;">
		<div style="background-image:url('<?php echo $website_url; ?>/sites/default/files/assets/pattern/extralight.png')" class="pattern-outer">
			<div class="smallspace-wrapper clearfix pattern-inner">
				<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
					<p class="copy-text text-align-justify"><?php print $text_grauer_kasten_pdf; ?></p>
					<p class="pdb2-processing-method-text text-align-justify">
						<?php print Wcms_ContentboxController::getContenbox('pdb---datasheet---processing-method', $language_id); ?>:
						<?php
						$processingnotes_all = $this->getSerieProcessing($serie['id']);
						// var_dump($processingnotes_all);
						$str_processingnote_type = '';
						if (true == isset($processingnotes_all['processing_im'])) {
							$processing_type = 'injection';
							$str_processingnote_type = Wcms_ContentboxController::getContenbox($processing_type, $language_id);
						}
						if (true == isset($processingnotes_all['processing_ex'])) {
							$processing_type = 'extrusion';
							if (strlen($str_processingnote_type) > 1) {
								$str_processingnote_type .= ', ' . Wcms_ContentboxController::getContenbox($processing_type, $language_id);
							} else {
								$str_processingnote_type .= Wcms_ContentboxController::getContenbox($processing_type, $language_id);
							}
						}
						echo $str_processingnote_type;
						?>
							<br /><b>
										<?php echo Wcms_ContentboxController::getContenbox('pdb---datasheet---srs-color', $language_id); ?>:</b>
										<?php
										// echo $compound["srs_farbe_db"];
										$arr_farben = array();
										foreach ($compounds As $compound) {
											if (false == in_array(trim($compound['srs_farbe_db']), $arr_farben)) {
												$arr_farben[] = trim(str_replace('<', '&lt;', str_replace(array('<p>', '</p>', '<P>', '</P>'), array('', ' '), $compound['srs_farbe_db'])));
											}
										}
										// if (count($arr_farben) < 1) {
										$arr_farben = $this->getSerieColor($serie['id'], $language_id);
										// }
										print ucwords(implode(', ', $arr_farben));
										?>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

<section class="serie">
  <div class="container ct-u-padding-bottom-40">
    <div class="row">

			<?php
			$height = 137;

			$height = 89;
			// getCompoundTypicalapplication aus TpePdbModel.php
			$serie['anwendungsbereiche'] = $this->getSerieTypicalapplication($serie['id']);
			// getCompoundMaterialadvantages aus TpePdbModel.php
			$serie['materialvorteile'] = $this->getSerieMaterialadvantages($serie['id']);

			if (count($serie['materialvorteile']) > count($serie['anwendungsbereiche'])) {
				$height_add = count($serie['materialvorteile']) * 30;
			} else {
				$height_add = count($serie['anwendungsbereiche']) * 30;
			}
			$height = $height_add + $height;

			?>
			<!-- Anwendungsbereiche -->
			<div class="anwendungsbereiche paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-extralight dark-font col-sm-12 vertical-center_" style="height: <?php echo $height; ?>px;">
				<div style="background-image:url('<?php echo $website_url; ?>/sites/default/files/assets/pattern/extralight.png')" class="pattern-outer">
					<div class="smallspace-wrapper clearfix pattern-inner">
						<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
							<h2><?php print Wcms_ContentboxController::getContenbox('pdb---typical-applications', $language_id); ?></h2>
								<ul>
									<?php foreach ($serie['anwendungsbereiche'] as $anwendungsbereich) { ?>
										<li>
											<?php print trim(str_replace(array('<p>', '</p>', '<P>', '</P>'), array('', ' '), $anwendungsbereich)); ?>
										</li>
									<?php } ?>
								</ul>
							<p>&nbsp;</p>
						</div>
					</div>
				</div>
			</div>
			<!-- MATERIALVORTEILE -->
			<div class="materialvorteile paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-extralight dark-font col-sm-12" style="height: <?php echo $height; ?>px;">
				<div style="background-image:url('<?php echo $website_url; ?>/sites/default/files/assets/pattern/extralight.png')" class="pattern-outer">
					<div class="smallspace-wrapper clearfix pattern-inner">
						<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
							<h2>
								<?php print Wcms_ContentboxController::getContenbox('pdb---material-advantages', $language_id); ?>
							</h2>
							<ul>
								<?php foreach ($serie['materialvorteile'] as $materialvorteile) { ?>
									<?php // if (true === empty($materialvorteile)) { continue; } ?>
									<li>
										<?php print trim(str_replace(array('<p>', '</p>', '<P>', '</P>'), array('', ' '), $materialvorteile)); ?>
									</li>
								<?php } ?>
							</ul>
							<p>&nbsp;</p>
						</div>
					</div>
				</div>
			</div>
			
			<!-- Regulations Approvals-->
			<?php
			// echo $this->getCompoundApproval($compound['id']);
			$serie['verordnungen'] = $this->getSerieApproval($serie['id']);
			$height = 84;
			$height_add = count($serie['verordnungen']) * 31;
			$height = $height_add + $height;
			?>
			<?php if (count($serie['verordnungen']) > 0) { ?>
			<div class="verordnungenzulassungen  paragraph clearfix paragraph--type--pattern paragraph--view-mode--default color-scheme-extralight dark-font col-sm-24 vertical-center_" style="height: <?php echo $height; ?>px;">
				<div style="background-image:url('<?php echo $website_url; ?>/sites/default/files/assets/pattern/extralight.png')" class="pattern-outer">
					<div class="smallspace-wrapper clearfix pattern-inner">
						<div class="paragraph clearfix paragraph--type--textblock paragraph--view-mode--default col-sm-24">
							<h2><?php print Wcms_ContentboxController::getContenbox('regulations-approvals', $language_id); ?></h2>
								<ul>
									<?php
									// echo $this->getCompoundApproval($compound['id']);

									?>
									<?php
									// $serie["verordnungen"] = array('FDA Compliant', 'Halogenfrei (ISO63216-1)', 'DBL5562', 'UL94');
									foreach ($serie['verordnungen'] as $verordnung) {
										?>
										<li>
											<?php print trim(str_replace(array('<p>', '</p>', '<P>', '</P>'), array('', ' '), $verordnung)); ?>
										</li>
									<?php } ?>
								</ul>
							<p>&nbsp;</p>
						</div>
					</div>
				</div>
			</div>
			<?php } ?>
<?php include_once ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'elements' . DS . 'datasheetseries.phtml'; ?>
<?php
	// $path_include = ASSETS . DS . "tpepdb2" . DS . "templates" . DS . "elements" . DS . "downloadcenter.phtml";
	include_once ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'elements' . DS . 'downloadcenter.phtml';
?>
<?php  // include_once ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'elements' . DS . 'sdsseries.phtml';
?>
			

  </div>
</section>

<?php } ?>