<div class="ncw-main-tabs">
    <ul class="ncw-main-tabs-container">
        <li class="ncw-main-tab"><a href="#"><?php if ($this->languages_num > 1) { ?> <?php print T_('Site container data'); ?><?php } else { print T_('Site data'); }  ?></a></li>
        <li class="ncw-main-tab"><a href="#"><?php print T_('Behaviour'); ?></a></li>
        <li class="ncw-main-tab"><a href="#"><?php print T_('Access'); ?></a></li>
        <?php if ($this->languages_num > 1) { ?><li class="ncw-main-tab"><a href="#"><?php print T_('Translations'); ?></a></li><?php } ?>
        <?php foreach ($this->sitetype_tabs as $sitetype_main_tab_method => $sitetype_main_tab_options) { ?>
            <?php
            if ($sitetype_main_tab_method == 'data' || $sitetype_main_tab_method == 'behaviour') {
                continue;
            }
            ?>
            <li class="ncw-main-tab"><a href="#"><?php print $sitetype_main_tab_options['name']; ?></a></li>
        <?php } ?>
        <?php if ($this->languages_num < 2) { ?>
            <?php foreach ($this->sitelanguagetype_tabs as $sitelanguagetype_main_tab_method => $sitelanguagetype_main_tab_options) { ?>
                <?php
                if ($sitelanguagetype_main_tab_method == 'data' || $sitelanguagetype_main_tab_method = 'behaviour') {
                    continue;
                }
                ?>
                <li class="ncw-main-tab"><a href="#"><?php print T_($sitelanguagetype_main_tab_options['name']); ?></a></li>
            <?php } ?>
        <?php } ?>
    </ul>
    <?php print $this->form->create('ncw-site', array('onsubmit' => 'return false;')); ?>
    <div class="ncw-main-tab-contents">
        <div class="ncw-main-tab-content">
            <ul class="ncw-tabs-container">
                <li class="ncw-tab"><a href="#"><?php print T_('Main'); ?></a></li>
                <?php if ($this->languages_num < 2) { ?><li class="ncw-tab"><a href="#"><?php print T_('Meta data'); ?></a></li><?php } ?>
                <?php if (true === isset($this->sitetype_tabs['data']['subtabs'])) { ?>
                    <?php foreach ($this->sitetype_tabs['data']['subtabs'] as $sub_tab_options) { ?>
                        <li class="ncw-tab"><a href="#"><?php print T_($sub_tab_options['name']); ?></a></li>
                    <?php } ?>
                <?php } ?>
                <?php
                if ($this->languages_num < 2
                    && true === isset($this->sitelanguagetype_tabs['data']['subtabs'])
                ) {
                ?>
                    <?php foreach ($this->sitelanguagetype_tabs['data']['subtabs'] as $sub_tab_options) { ?>
                        <li class="ncw-tab"><a href="#"><?php print T_($sub_tab_options['name']); ?></a></li>
                    <?php } ?>
                <?php } ?>
            </ul>
            <?php print $this->form->input("id", array('type' => 'hidden', 'value' => $this->site_id)); ?>
            <div class="ncw-tab-contents">
                <div class="ncw-tab-content ncw-tab-content-full">
                    <?php if (true === $this->permissions['/wcms/component/all']) { ?>
                        <p>
                            <a href="javascript: ncw.wcms.component(<?php print $this->site_id ?>);" class="ncw-action">
                                <?php print T_('Show components'); ?>
                            </a>
                        </p>
                    <?php } ?>
                    <br class="ncw-clear" />
                    <p>
                        <?php print T_('ID');?>: <?php print $this->site_id; ?><br />
                        <?php print T_('Name');?>: <?php print $this->site_name; ?><br />
                        <?php if ($this->languages_num > 1) { ?>
                            <?php print T_('URL');?>: <?php print $this->url; ?><br />
                        <?php } else { ?>
                            <?php print T_('URL');?>: <a href="<?php print $this->url; ?>"><?php print $this->url; ?></a><br />
                        <?php } ?>
                    </p>
                    <?php print $this->form->input("name", array('maxlength' => 100, 'title' => T_('Name in URL') . '. ' . T_('For example: /en/<strong>home</strong>'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Name in URL')))); ?>
                    <?php if ($this->languages_num < 2) { ?>
                        <?php print $this->form->input("Sitelanguage.id", array('type' => 'hidden')); ?>
                        <?php print $this->form->input("Sitelanguage.name", array('maxlength' => 100, 'title' => T_('This is the name which is shown in a navigation'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Navigation name')))); ?>
                        <?php print $this->form->input("Sitelanguage.title", array('maxlength' => 100, 'title' => T_('This text is shown in the browser bar and is used as title text of a search result of any search engine'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Title')))); ?>
                        <div class="ncw-input-container">
                            <label class="ncw-label" for="sitelanguage_home"><?php print T_('Is home site?');?></label>
                            <?php print $this->form->input("Sitelanguage.home", array('type' => 'checkbox', 'class' => 'ncw-checkbox', 'div' => array('class' => 'ncw-radios-checkbox'), 'label' => FALSE)); ?>
                        </div>
                    <?php } ?>

                    <?php print $this->sitetype_content['data']['main']; ?>
                    <?php if ($this->languages_num < 2) { ?>
                        <?php print $this->sitelanguagetype_content['data']['main']; ?>
                    <?php } ?>
                </div>
                <?php if ($this->languages_num < 2) { ?>
                    <div class="ncw-tab-content ncw-tab-content-full">
                        <?php print $this->form->input('Sitelanguage.keywords', array('type' => 'textarea', 'maxlength' => 255, 'title' => T_('keywords are used by meta data search engines. Google does not look at keywords anymore (negligible)'), 'class' => 'ncw-textarea', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Keywords')))); ?>
                        <?php print $this->form->input('Sitelanguage.description', array('type' => 'textarea', 'maxlength' => 255, 'title' => T_('The description is used by search engines. It will be displayed after the title text of a search result'), 'class' => 'ncw-textarea', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Description')))); ?>
                        <?php print $this->form->input("Sitelanguage.author", array('maxlength' => 100, 'title' => T_('Author of the document. Used by some search engines (negligible)'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Author')))); ?>
                        <?php print $this->form->input('Sitelanguage.changefreq', array('type' => 'select', 'options' => $this->changefreq, 'title' => T_('Changefrequency of the site. Beware that wrong information may not have any effect'), 'class' => 'ncw-select', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Changefreq')))); ?>
                        <?php print $this->form->input('Sitelanguage.priority', array('type' => 'select', 'options' => $this->priority, 'title' => T_('Priority of the site. Beware that wrong information may not have any effect'), 'class' => 'ncw-select', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Priority')))); ?>

                        <?php print $this->sitelanguagetype_content['data']['main']; ?>
                    </div>
                <?php } ?>
                <?php if (true === isset($this->sitetype_tabs['data']['subtabs'])) { ?>
                    <?php foreach ($this->sitetype_tabs['data']['subtabs'] as $sub_tab_method => $sub_tab_options) { ?>
                        <div class="ncw-tab-content ncw-tab-content-full">
                            <?php print $this->sitetype_content['data'][$sub_tab_method]; ?>
                        </div>
                    <?php } ?>
                <?php } ?>
                <?php
                if ($this->languages_num < 2
                    && true === isset($this->sitelanguagetype_tabs['data']['subtabs'])
                ) {
                ?>
                    <?php foreach ($this->sitelanguagetype_tabs['data']['subtabs'] as $sub_tab_method => $sub_tab_options) { ?>
                        <div class="ncw-tab-content ncw-tab-content-full">
                            <?php print $this->sitelanguagetype_content['data'][$sub_tab_method]; ?>
                        </div>
                    <?php } ?>
                <?php } ?>
            </div>
        </div>
        <div class="ncw-main-tab-content">
            <ul class="ncw-tabs-container">
                <li class="ncw-tab"><a href="#"><?php print T_('Main'); ?></a></li>
                <li class="ncw-tab"><a href="#"><?php print T_('Miscellaneous'); ?></a></li>
                <?php if (true === isset($this->sitetype_tabs['behaviour']['subtabs'])) { ?>
                    <?php foreach ($this->sitetype_tabs['behaviour']['subtabs'] as $sub_tab_options) { ?>
                        <li class="ncw-tab"><a href="#"><?php print T_($sub_tab_options['name']); ?></a></li>
                    <?php } ?>
                <?php } ?>
            </ul>
            <div class="ncw-tab-contents">
                <div class="ncw-tab-content ncw-tab-content-full">
                    <h2><?php print T_('Type & look'); ?></h2>
                    <?php print $this->form->input("sitetype_id", array('type' => 'select', 'options' => $this->sitetypes, 'title' => T_('Choose a sitetype. For example redirect if you want this site to redirect to a other site'), 'class' => 'ncw-select', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Site type')))); ?>
                    <?php print $this->form->input("sitetemplate_id", array('type' => 'select', 'options' => $this->arr_sitetemplates, 'title' => T_('Look of the site'), 'class' => 'ncw-select', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Site template')))); ?>
                    <h2><?php print T_('Appearance'); ?></h2>
                    <div class="ncw-input-container">
                        <label class="ncw-label"><?php print T_('Navigations'); ?></label>
                        <div class="ncw-radios-checkbox">
                        <?php $count = 0; ?>
                        <?php foreach ($this->arr_navtemplates as $navigation_name => $navigation_id) { ?>
                            <?php $checked = ''; ?>
                            <?php if (true === in_array($navigation_id, $this->set_navtemplates)) { ?>
                                <?php $checked = 'checked="checked"';?>
                            <?php } ?>
                            <input type="checkbox" value="<?php print $navigation_id; ?>" <?php print $checked; ?> name="data[SiteNavtemplate][<?php print $count; ?>][navtemplate_id]" id="site_navtemplate_navtemplate_id_<?php print $navigation_id; ?>"/>
                            <label for="site_navtemplate_navtemplate_id_<?php print $navigation_id; ?>"><?php print $navigation_name; ?></label>
                            <?php ++$count; ?>
                        <?php } ?>
                        </div>
                    </div>
                    <div class="ncw-input-container">
                        <label class="ncw-label" for="site_parent_id"><?php echo T_('Parent site');?></label>
                        <select id="site_parent_id" name="data[Site][parent_id]" class="ncw-select" title="<?php print T_('Where this site will be located'); ?>">
                            <?php print $this->parent_options; ?>
                        </select>
                    </div>
                    <?php print $this->form->input('current_parent_id', array('type' => 'hidden', 'value' => $this->parent_id)); ?>
                    <?php print $this->form->input("position", array('type' => 'select', 'options' => $this->position_options, 'title' => T_('Position of the component within a content area'), 'class' => 'ncw-select', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Position')))); ?>
                    <?php print $this->form->input('curent_position', array('type' => 'hidden', 'value' => $this->current_position)); ?>
                    <h2><?php print T_('Schedule'); ?></h2>
                    <div class="ncw-input-container">
                        <label class="ncw-label" for="site_schedule"><?php print T_('Do you want to schedule this site?'); ?></label>
                        <?php print $this->form->input("schedule", array('type' => 'checkbox', 'class' => 'ncw-checkbox', 'div' => array('class' => 'ncw-radios-checkbox ncw-schedule-check'), 'label' => FALSE)); ?>
                    </div>
                    <div class="ncw-schedule <?php if (true === $this->schedule) { ?> ncw-schedule-show<?php } ?>">
                        <?php print $this->form->input('publish_date', array('title' => T_('On which date the site will be viewable'), 'class' => 'ncw-input ncw-datepick', 'value' => $this->site_publish[0], 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Publish date')))); ?>
                        <?php print $this->form->input('publish_time', array('title' => T_('On which time the site will be viewable'), 'class' => 'ncw-input ncw-timepick', 'value' => substr($this->site_publish[1], 0, 5), 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Publish time')))); ?>
                        <?php print $this->form->input('expire_date', array('title' => T_('On which date the site will expire'), 'class' => 'ncw-input ncw-datepick', 'value' => $this->site_expire[0], 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Expire date')))); ?>
                        <?php print $this->form->input('expire_time', array('title' => T_('On which time the site will expire'), 'class' => 'ncw-input ncw-timepick', 'value' => substr($this->site_expire[1], 0, 5), 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Expire time')))); ?>
                    </div>

                    <?php print $this->sitetype_content['behaviour']['main']; ?>
                </div>
                <div class="ncw-tab-content ncw-tab-content-full">
                    <div class="ncw-input-container">
                        <label class="ncw-label" for="site_cache"><?php print T_('Cache'); ?></label>
                        <?php print $this->form->input("cache", array('type' => 'checkbox', 'class' => 'ncw-checkbox', 'div' => array('class' => 'ncw-radios-checkbox'), 'label' => FALSE)); ?>
                    </div>
                    <div id="cache" <?php if (false === $this->cache) { ?>class="cache"<?php } ?>>
                        <?php print $this->form->input('cache_exparation', array('title' => T_('Cache exparation'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Cache exparation')))); ?>
                    </div>
                    <div class="ncw-input-container">
                        <label class="ncw-label" for="site_permalink"><?php print T_('Permalink?'); ?></label>
                        <?php print $this->form->input("permalink", array('type' => 'checkbox', 'class' => 'ncw-checkbox', 'div' => array('class' => 'ncw-radios-checkbox'), 'label' => FALSE)); ?>
                    </div>

                    <?php print $this->sitetype_content['behaviour']['miscellaneous']; ?>
                </div>
                <?php if (true === isset($this->sitetype_tabs['behaviour']['subtabs'])) { ?>
                    <?php foreach ($this->sitetype_tabs['behaviour']['subtabs'] as $sub_tab_method => $sub_tab_options) { ?>
                        <div class="ncw-tab-content ncw-tab-content-full">
                            <?php print $this->sitetype_content['behaviour'][$sub_tab_method]; ?>
                        </div>
                    <?php } ?>
                <?php } ?>
            </div>
        </div>
        <div class="ncw-main-tab-content">
            <h2><?php print T_('Site is only viewable for'); ?>:</h2>
            <div class="ncw-input-container">
                <label class="ncw-label" for="site_private"><?php print T_('logged in users'); ?></label>
                <?php print $this->form->input("private", array('type' => 'checkbox', 'class' => 'ncw-checkbox', 'div' => array('class' => 'ncw-radios-checkbox'), 'label' => FALSE)); ?>
            </div>
            <h2><?php print T_('From groups'); ?>:</h2>
            <?php if (true === is_array($this->group_options)) {?>
                <div class="ncw-input-container">
                    <label class="ncw-label" for="usergroup_usergroup_id"><?php print T_('Groups'); ?></label>
                    <select id="usergroup_usergroup_id" class="ncw-select" title="<?php print T_('Usergroup which will be allowed to access this site'); ?>">
                        <?php foreach ($this->group_options as $group) { ?>
                        <option id="ncw-private-group-<?php print $group->getId(); ?>" value="<?php print $group->getId(); ?>"><?php print str_repeat('--', $group->getLevel() - 1) . ' ' . $group->getName(); ?></option>
                        <?php } ?>
                    </select>
                </div>
                <a href="javascript: void(0);" id="ncw-add-private-group" class="ncw-action"><?php print T_('Add'); ?></a>
            <?php } else { ?>
                <span class="ncw-warning"><?php print T_('All groups are added'); ?></span>
            <?php } ?>
            <br class="ncw-clear" /><br />
            <table class="ncw-table">
               <thead>
                   <tr>
                       <th><?php print T_('Name'); ?></th>
                       <th><?php print T_('Options'); ?></th>
                   </tr>
               </thead>
               <tbody id="ncw-private-groups">
                <?php if (false === empty($this->groups)) { ?>
                    <?php foreach ($this->groups as $group) { ?>
                        <tr id="ncw-added-private-group-<?php print $group['id']; ?>">
                            <td><?php print $group['name']; ?></td>
                            <td class="ncw-table-td-icons">
                                <a href="javascript: ncw.wcms.site.privateGroups.remove(<?php print $group['id']; ?>);"><?php print $this->html->image("icons/16px/delete.png", false, array('alt' => T_('Delete'), 'title' => T_('Delete'))); ?></a>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
               </tbody>
            </table>

            <?php print $this->sitetype_content['access']; ?>
        </div>
        <?php if ($this->languages_num > 1) { ?>
            <div class="ncw-main-tab-content">
                <?php if (true === $this->permissions['/wcms/sitelanguage/new']) { ?>
                    <p>
                        <a href="javascript: ncw.wcms.sitelanguage.loadNew(<?php print $this->site_id?>, null); ">
                            <div class="ncw-action"><?php print T_('New translation'); ?></div>
                        </a>
                    </p>
                <?php } ?>
                <br class="ncw-clear" /><br />
                <table class="ncw-table">
                    <thead>
                        <tr>
                            <th><?php print T_('Name'); ?></th>
                            <th><?php print T_('Options'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php if (false === empty($this->sitelanguages)) { ?>
                        <?php foreach ($this->sitelanguages as $obj_sitelanguage) { ?>
                            <tr>
                                <td>
                                    <a href="javascript: ncw.wcms.site.loadTranslation(<?php print $obj_sitelanguage->getId(); ?>);">
                                        <?php print $this->html->image("country_flags/" . $obj_sitelanguage->Language->getShortcut() . ".gif", false, array("alt" => $obj_sitelanguage->Language->getName(), "title" => $obj_sitelanguage->Language->getNameEncoded())); ?>
                                    </a>
                                    <a href="javascript: ncw.wcms.site.loadTranslation(<?php print $obj_sitelanguage->getId(); ?>);">
                                        <?php print $obj_sitelanguage->getNameEncoded(); ?>
                                    </a>
                                </td>
                                <td class="ncw-table-td-icons">
                                    <a href="javascript: ncw.wcms.site.loadTranslation(<?php print $obj_sitelanguage->getId(); ?>);">
                                        <?php print $this->html->image("icons/16px/pencil.png", false, array('alt' => T_('Edit'), 'title' => T_('Edit'))); ?>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } ?>
                    </tbody>
                </table>

                <?php print $this->sitetype_content['translations']; ?>
            </div>
        <?php } ?>
        <?php foreach ($this->sitetype_tabs as $sitetype_main_tab_method => $sitetype_main_tab_options) { ?>
            <?php
            if ($sitetype_main_tab_method == 'data' || $sitetype_main_tab_method = 'behaviour') {
                continue;
            }
            ?>
            <div class="ncw-main-tab-content">
            <?php if (true === isset($sitetype_main_tab_options['subtabs'])) { ?>
                <ul class="ncw-tabs-container">
                    <?php foreach ($sitetype_main_tab_options['subtabs'] as $sitetype_sub_tab_options) { ?>
                        <li class="ncw-tab"><a href="#"><?php print T_($sitetype_sub_tab_options['name']); ?></a></li>
                    <?php } ?>
                </ul>
                <div class="ncw-tab-contents">
                    <?php foreach ($sitetype_main_tab_options['subtabs'] as $sitetype_sub_tab_method => $sitetype_sub_tab_options) { ?>
                        <div class="ncw-tab-content ncw-tab-content-full">
                            <?php print $this->sitetype_content[$sitetype_main_tab_method][$sitetype_sub_tab_method]; ?>
                        </div>
                    <?php } ?>
                </div>
            <?php
            } else {
                print $this->sitetype_content[$sitetype_main_tab_method];
            }
            ?>
            </div>
        <?php } ?>
        <?php if ($this->languages_num < 2) { ?>
            <?php foreach ($this->sitetype_tabs as $sitelanguagetype_main_tab_method => $sitelanguagetype_main_tab_options) { ?>
                <?php
                if ($sitelanguagetype_main_tab_method == 'data' || $sitelanguagetype_main_tab_method == 'behaviour') {
                    continue;
                }
                ?>
                <div class="ncw-main-tab-content">
                <?php if (true === isset($sitelanguagetype_main_tab_options['subtabs'])) { ?>
                    <ul class="ncw-tabs-container">
                        <?php foreach ($sitelanguagetype_main_tab_options['subtabs'] as $sitelanguagetype_sub_tab_options) { ?>
                            <li class="ncw-tab"><a href="#"><?php print T_($sitelanguagetype_sub_tab_options['name']); ?></a></li>
                        <?php } ?>
                    </ul>
                    <div class="ncw-tab-contents">
                        <?php foreach ($sitelanguagetype_main_tab_options['subtabs'] as $sitelanguagetype_sub_tab_method => $sitelanguagetype_sub_tab_options) { ?>
                            <div class="ncw-tab-content ncw-tab-content-full">
                                <?php print $this->sitelanguagetype_content[$sitelanguagetype_main_tab_method][$sitelanguagetype_sub_tab_method]; ?>
                            </div>
                        <?php } ?>
                    </div>
                <?php
                } else {
                    print $this->sitelanguagetype_content[$sitelanguagetype_main_tab_method];
                }
                ?>
                </div>
            <?php } ?>
        <?php } ?>
    </div>
    <?php print $this->form->end(); ?>
</div>
<div class="ncw-status-action-bar">
    <div class="ncw-status-message"></div>
    <ul class="ncw-actions">
        <?php
        if (true === $this->permissions['/wcms/site/unpublish']
            && $this->site_status === 'published'
            || $this->site_status === 'modified'
        ) {
        ?>
            <li class="ncw-action"><a href="#" rel="site" class="ncw-unpublish-trigger ncw_unpublish_icon"><?php print T_('Unpublish'); ?></a></li>
        <?php } ?>
        <?php if (true === $this->permissions['/wcms/site/publish']) { ?>
            <li class="ncw-action"><a href="#" rel="site" class="ncw-publish-trigger ncw_publish_icon"><?php print T_('Publish'); ?></a></li>
        <?php } ?>
        <?php if (true === $this->permissions['/wcms/site/new']) { ?>
            <li class="ncw-action"><a href="#" rel="site" class="ncw-copy-trigger ncw_copy_icon"><?php print T_('Copy'); ?></a></li>
        <?php } ?>
        <?php if (true === $this->permissions['/wcms/site/delete']) { ?>
            <li class="ncw-action"><a href="#" rel="wcms/site" class="ncw-delete-trigger-ajax ncw_delete_icon"><?php print T_('Delete'); ?></a></li>
        <?php } ?>
        <li class="ncw-action"><a href="#" rel="wcms/site" class="ncw-save-trigger-ajax ncw_save_icon"><?php print T_('Save'); ?></a></li>
    </ul>
</div>