<h2><?php print T_('Redirect'); ?></h2>
<?php print $this->form->input('id', array('type' => 'hidden')); ?>
<?php print $this->form->input('url', array('maxlength' => 255, 'title' => T_('URL'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('URL')))); ?>
<div class="ncw-input-container">
    <label class="ncw-label" for="ncw-redirect_internal"><?php print T_('Internal'); ?></label>
    <select id="ncw-redirect_internal" class="ncw-select" title="<?php print T_('Internal'); ?>">
        <option>---</option>
        <?php foreach ($this->linklist as $link => $values) { ?>
        <option value="<?php print $link; ?>"<?php if ($this->link === $link) { ?> selected="selected"<?php } ?>><?php print $values['prefix'] . ' ' . $values['name']; ?></option>
        <?php } ?>
    </select>
</div>
<script type="text/javascript">
$('#ncw-redirect_internal').change(
    function () {
        var link = $(this).val();
        link_field_id = $(this).attr('id');
        link_field_id = link_field_id.split('_');
        link_field_id = 'redirect_url';
        if (link != '---') {
            $('#' + link_field_id).val(link);
        } else {
            $('#' + link_field_id).val('');
        }
    }
);
</script>