<div class="ncw-left">
    <div class="ncw-accordion">
        <h3 class="ncw-accordion-header current"><?php print T_('Contacts'); ?></h3>
        <div class="ncw-accordion-content ncw-accordion-current">
			<?php echo $this->form->create('ncw-contact-search', array('onsubmit' => 'ncw.contacts.contact.search(); return false;')); ?>
			<div class="ncw-input-container-small">
			    <label class="ncw-label-small" for="contact_search"><?php print T_('Search'); ?></label>
			    <input id="contact_search" class="ncw-input-small" type="text" title="<?php print T_('Search'); ?>" value="" name="s"/>
			</div>
			<input type="submit" style="display: none;"/>
			<p class="ncw-accordion-content-part-dark">
			    <a href="javascript: ncw.contacts.contact.search();" class="ncw_text_button_search"><?php print T_('Search'); ?></a>
			</p>
			<?php echo $this->form->end(); ?>		
			<?php if (true === $this->permissions['/contacts/group/new']) { ?>
				<p class="ncw-accordion-content-part-dark">
	                <a href="javascript: ncw.contacts.group.loadNew();" class="ncw_text_button_group_add"><?php print T_('New group'); ?></a>
	            </p>
            <?php } ?>
            <?php if (true === $this->permissions['/contacts/contact/new']) { ?>
	            <p class="ncw-accordion-content-part-dark">
	                <a href="javascript: ncw.contacts.contact.loadNew('private');" class="ncw_text_button_person_add"><?php print T_('New person'); ?></a>
	            </p>  
	            <p class="ncw-accordion-content-part-dark">
	                <a href="javascript: ncw.contacts.contact.loadNew('business');" class="ncw_text_button_building_add"><?php print T_('New company'); ?></a>
	            </p>       
            <?php } ?>
            <div class="ncw-groups-tree ncw-tree"></div>
        </div>
        <h3 class="ncw-accordion-header"><?php print T_('Favorites'); ?></h3>
        <div class="ncw-accordion-content favorites"></div>           
        <h3 class="ncw-accordion-header"><?php print T_('Recently viewed'); ?></h3>
        <div class="ncw-accordion-content recently_opened"></div>      
        <h3 class="ncw-accordion-header"><?php print T_('Recently added'); ?></h3>
        <div class="ncw-accordion-content recently_added"></div>               
    </div>  
</div>
<div class="ncw-right"></div>
<script type="text/javascript">
ncw.contacts.group.tree.permissions = {};
ncw.contacts.group.tree.permissions.group = {};
ncw.contacts.group.tree.permissions.group.addNew = <?php print ($this->permissions['/contacts/group/new'] ? 'true' : 'false'); ?>;
ncw.contacts.group.tree.permissions.group.edit = <?php print ($this->permissions['/contacts/group/edit'] ? 'true' : 'false'); ?>;
ncw.contacts.group(<?php print $this->contact_id; ?>);
</script>