<div class="ncw-main-tabs">
    <ul class="ncw-main-tabs-container">
    	<li class="ncw-option-tab"><a href="javascript: ncw.contacts.contact.load();"><?php print T_('Contacts of group') . ': '. $this->group_name; ?></a></li>
        <li class="ncw-main-tab"><a href="#"><?php print T_('Edit group'); ?></a></li>
    </ul>
    <div class="ncw-main-tab-contents">
        <div class="ncw-main-tab-content">
            <?php print $this->form->create('ncw-group'); ?>
            <?php print $this->form->input("id", array('type' => 'hidden', 'value' => $this->group_id)); ?>
            <?php print $this->form->input("name", array('maxlength' => 255, 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Name')))); ?>
            <div class="ncw-input-container">
                <label for="group_parent_id" class="ncw-label"><?php print T_('Parent Folder'); ?></label>
                <select id="group_parent_id" title="<?php print T_('Where this group will be located'); ?>" name="data[Group][parent_id]" class="ncw-select">
                    <?php print $this->groups_options; ?>
                </select>
            </div>
            <?php print $this->form->end(); ?>
        </div>
    </div>
</div>
<div class="ncw-status-action-bar">
    <div class="ncw-status-message"></div>
    <ul class="ncw-actions">
    	<?php if (true === $this->permissions['/contacts/group/delete']) { ?>
        	<li class="ncw-action"><a href="#" rel="contacts/group" class="ncw-delete-trigger-ajax ncw_delete_icon" rel="#ncw-delete"><?php echo T_('Delete'); ?></a></li>
        <?php } ?>
        <li class="ncw-action"><a href="#" rel="contacts/group" class="ncw-save-trigger-ajax ncw_save_icon"><?php print T_('Save'); ?></a></li>
    </ul>
</div>