<?php ob_start(); ?>
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td style="height: 70px"><img src="<?php print ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'images' . DS . 'tpe-logo-2019.png'; ?>" height="170" /></td>
        <!--<td align="right">
            <table cellpadding="0" cellspacing="0">
                <tr>
                    <td style="height: 28px;">&nbsp;</td>
                </tr>
                <tr>
                    <td><b style="font-size:16px;"><?php
                        if ($type == "serie" || $compound['status'] == 'portfolio') {
                            print Wcms_ContentboxController::getContenbox('pdb---datasheet---datasheet', $language_id);
                        } else {
                            //print Wcms_ContentboxController::getContenbox('pdb---datasheet---test-report', $language_id);
                            print Wcms_ContentboxController::getContenbox('pdb---datasheet---datasheet', $language_id);
                        }
                    ?></b>
                    </td>
                </tr>
            </table>
        </td>-->
    </tr>
    <tr>
        <td colspan="2" style="height: 14px;font-size: 2px;">&nbsp;</td>
    </tr>
    <tr>
        <td style="height: 70px"><img src="<?php print ASSETS . DS . 'tpepdb2' . DS . 'templates' . DS . 'images' . DS . 'symbol.png'; ?>" height="170" /></td>
    </tr>
</table>
<br />
<br />
<br /><br /><br /><br /><br />
<?php
if ($type == "serie") {
    include_once ASSETS . DS . "tpepdb2" . DS . "templates" . DS . "elements" . DS . "serie"  . DS . "serie_headline.phtml";
} else {
    include_once ASSETS . DS . "tpepdb2" . DS . "templates" . DS . "elements" . DS . "compound"  . DS . "compound_headline.phtml";
}
?>
<?php $pdf->header_content = ob_get_clean(); ?>