<div class="ncw-right">
    <?php print $this->form->create(); ?>
    <?php print $this->form->input("id", array('type' => 'hidden', 'value' => $this->language_id)); ?>
    <div class="ncw-main-tabs">
        <ul class="ncw-main-tabs-container">
        	<li class="ncw-option-tab"><?php print $this->html->link(T_('Back'), array('action' => 'all')); ?></li>
            <li class="ncw-main-tab"><a href="#"><?php print T_('Edit language'); ?></a></li>
        </ul>
        <div class="ncw-main-tab-contents">
            <div class="ncw-main-tab-content">
                <?php print $this->form->input("name", array('maxlength' => 100, 'title' => T_('The full language name'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Name')))); ?>
                <?php print $this->form->input("shortcut", array('maxlength' => 2, 'title' => T_('Shortcut of the language name'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Shortcut')))); ?>
                <div class="ncw-input-container">
                    <label class="ncw-label" for="language_active"><?php print T_('Is this language active (live)?'); ?></label>
                    <?php print $this->form->input("active", array('type' => 'checkbox', 'class' => 'ncw-checkbox', 'div' => array('class' => 'ncw-radios-checkbox'), 'label' => FALSE)); ?>
                </div>
                <p>
                    <?php print T_('If not then the language and all it\'s translations will not be displayed on the website'); ?>
                </p>
                <div class="ncw-input-container">
                    <label class="ncw-label" for="language_active"><?php print T_('Copies content from the master language?'); ?></label>
                    <?php print $this->form->input("copies", array('type' => 'checkbox', 'class' => 'ncw-checkbox', 'div' => array('class' => 'ncw-radios-checkbox'), 'label' => FALSE)); ?>
                </div>
           </div>
        </div>
    </div>
    <div class="ncw-status-action-bar">
        <div class="ncw-status-message"></div>
        <ul class="ncw-actions">
            <li class="ncw-action"><a href="<?php print $this->html->url(array('action' => T_('Delete'), 'id' => $this->language_id)); ?>" class="ncw-delete-trigger ncw_delete_icon" rel="#ncw-delete"><?php print T_('Delete'); ?></a></li>
            <li class="ncw-action"><a href="#" class="ncw-save-trigger ncw_save_icon"><?php print T_('Save'); ?></a></li>
        </ul>
    </div>
    <?php print $this->form->end(); ?>
</div>