<div class="ncw-main-tabs">
    <ul class="ncw-main-tabs-container">
        <li class="ncw-main-tab"><a href="#"><?php print T_('New translation'); ?></a></li>
    </ul>
    <div class="ncw-main-tab-contents">
        <div class="ncw-main-tab-content">
            <p>
                <a href="javascript: ncw.wcms.site(<?php print $this->site_id ?>);">
                    <div class="ncw-action"><?php print T_('Back'); ?></div>
                </a>
            </p>
            <br class="ncw-clear" /><br />
            <?php print $this->form->create('ncw-sitelanguage', array('onsubmit' => 'return false;')); ?>
            <?php print $this->form->input("site_id", array('type' => 'hidden', 'value' => $this->site_id)); ?>
            <?php if (false === empty($this->arr_options)) { ?>
                <?php print $this->form->input("name", array('maxlength' => 100, 'title' => T_('This is the name which is shown in a navigation'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Navigation name')))); ?>
                <?php print $this->form->input("language_id", array('type' => 'select', 'options' => $this->arr_options, 'title' => T_('Language of the site'), 'class' => 'ncw-select', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Language')))); ?>
            <?php } else { ?>
                <?php print T_('All translations are already added!'); ?>
            <?php } ?>
            <?php print $this->form->end(); ?>
        </div>
    </div>
</div>
<div class="ncw-status-action-bar">
    <div class="ncw-status-message"></div>
    <ul class="ncw-actions">
        <li class="ncw-action"><a href="#" rel="wcms/sitelanguage" class="ncw-new-trigger-ajax ncw_save_icon"><?php print T_('Save'); ?></a></li>
    </ul>
</div>