<?php $columns = array(); ?>
<?php $order = array("103" => 0, "106" => 1, "104" => 2, "101" => 3, "77" => 4, "87" => 5, "232" => 6, "242" => 7); ?>
<?php $next_column = count($order) + 1; ?>
<?php foreach ($compound as $key => $value) { ?>
    <?php if ((int) $key > 0 && true === isset($labels["compound"][$key]) && false === empty($value)) { ?>
        <?php
        if (true === isset($order[$key])) {
            $pos = $order[$key];
        } else {
            $pos = ++$next_column;
        }
        $columns[$pos] = array("", 0, $key);
        ?>
    <?php } ?>
<?php } ?>
<?php if (count($columns > 0)) { ?>
    <?php ksort($columns); ?>
    <?php
    $arr_note = $arr_notecount = array();
    $notecount = 0;
    $note_texts = array();
    foreach ($columns as $values) {
        $key = $values[2];
        $note_name = $key . "_note";
        if (true === isset($labels["compound"][$note_name])) {
            $note_text = str_replace(array('<P>', '</P>'), '', trim($labels["compound"][$note_name]));
            if (false == in_array($note_text, $note_texts)) {
                $note_texts[$key] = $note_text;
                $notecount++;
                $arr_notecount[$key] = ' <sup>' . $notecount . '</sup>';
                $arr_note[$key] = '<sup>' . $notecount . '</sup> ' .  $note_text . '<br />';
            } else {
                foreach ($note_texts as $note_key => $note_value) {
                    if ($note_value == $note_text) {
                        $arr_notecount[$key] = $arr_notecount[$note_key];
                    }
                    //$arr_note[$key] = $arr_note[$key];
                }
            }
        }
    }
    ?>
    <?php $first = true; ?>
    <?php foreach ($columns as $column) { ?>
        <?php $key = $column[2]; ?>
        <?php $value = $compound[$column[2]]; ?>
                   <?php //var_dump($key . " - " . $value); ?>
        <?php if ((int) $key > 0 && true === isset($labels["compound"][$key]) && $labels["compound"][$key] != "" && $labels["compound"][$key] != "QPMK_NORM" && false === empty($compound[$column[2]])) { ?>
            <?php if (true === $first) { ?>
            <table class="compound-table" style="width: 100%;" cellspacing="0" cellpadding="0">
                <tr style="background-color: #18529D; text-align: left;">
                    <th colspan="3" style="height: 30px; text-align: left;"><?php print td_value(Wcms_ContentboxController::getContenbox('pdb---datasheet---mechanical-properties', $language_id), $font_size_table, true, '#fff'); ?></th>
                </tr>
                <?php $first = false; ?>
            <?php } ?>
                    <tr>
                        <?php
                        $norm = "";
                        $prop_name = "";
                        if (true === isset($compound[$key . "_norm"]) && false === empty($compounds[0][$key . "_norm"])) {
                            $prop_name = str_replace($compound[$key . "_norm"], "", $labels["compound"][$key]);
                            $prop_name = explode("DIN", $prop_name);
                            $prop_name = "<b>" . trim($prop_name[0]) . "</b>";
                            $norm = $compound[$key . "_norm"];
                        } else {
                            $label = $labels["compound"][$key];
                            if (false !== strstr($label, "DIN")) {
                                $prop_name_exploded = explode("DIN", $label);
                                $prop_name = "<b>" . $prop_name_exploded[0] . "</b>";
                                if (true === isset($prop_name_exploded[1])) {
                                    $norm = "DIN " . $prop_name_exploded[1];
                                }
                            } else if (false !== strstr($label, "Norm")) {
                                $prop_name_exploded = explode("Norm", $label);
                                $prop_name = "<b>" . $prop_name_exploded[0] . "</b>";
                                if (true === isset($prop_name_exploded[1])) {
                                    $norm = "Norm " . $prop_name_exploded[1];
                                }
                            } else {
                                $prop_name = "<b>" . $label . "</b>";
                            }
                        }
                        if (true === isset($arr_notecount[$key])) {
                             $prop_name .= $arr_notecount[$key];
                        }
                        ?>
                        <td style="<?php print td_styles($font_size_table, "35%"); ?>"><?php print td_value($prop_name, $font_size_table, true); ?></td>
                        <?php
                        $value = $compound[$column[2]];
                        if ($language == "de") {
                            $value = str_replace(".", ",", $value);
                        }
                        if (true === isset($compound[$key . "_unit"])) {
                            $value .= " " . $compound[$key . "_unit"];
                        }
                        ?>
                        <td style="<?php print td_styles($font_size_table, "30%"); ?>"><?php print td_value($value, $font_size_table); ?></td>
                        <td style="<?php print td_styles($font_size_table, "35%"); ?>"><?php print td_value($norm, $font_size_table); ?>
                            <?php if (true === isset($compound[$key . "_din_norm"])) { ?>
                                <?php print td_value($compound[$key . "_din_norm"], $font_size_table); ?>
                            <?php } ?>
                        </td>
                    </tr>
        <?php } ?>
    <?php } ?>
    <?php if (false === $first) { ?></table><?php } ?>
<?php } ?>