<div class="ncw-main-tabs">
    <ul class="ncw-main-tabs-container">
        <li class="ncw-main-tab"><a href="#"><?php echo T_('Overview'); ?></a></li>
    </ul>
    <div class="ncw-main-tab-contents">

        <div class="ncw-main-tab-content">

			<table >
				
				<tr>
					
					<td style="width: 250px;" valign="top">
						<h2><?php print T_('Favorites'); ?></h2>
						<div class="favorites"></div>						
					</td>					
					
					<td style="width: 250px;" valign="top">
						<h2><?php print T_('Recently viewed'); ?></h2>
						<div class="recently_opened"></div>    
					</td>
					
					<td style="width: 250px;" valign="top">
						<h2><?php print T_('Recently added'); ?></h2>
						<div class="recently_added"></div>						
					</td>
					
				</tr>
				
			</table>
						
		</div>
    </div>
</div>
