<div id="ncw-loading-overlay"></div>
<?php print $this->html->image('throbber_big_grey.gif', false, array('id' => 'ncw-loading-throbber')); ?>
<div id="ncw-alert">
    <h2 id="ncw-alert-head"></h2>
    <p id="ncw-alert-body"></p>
    <p id="ncw-alert-options">
      <button id="ncw-alert-yes"><?php print T_('Ok'); ?></button>
    </p>
</div>
<div id="ncw-delete">
    <h2 id="ncw-delete-head"></h2>
    <p id="ncw-delete-body"></p>
    <p id="ncw-delete-options">
        <button id="ncw-delete-yes"><?php print T_('Yes'); ?></button>
        <button id="ncw-delete-no"><?php print T_('No'); ?></button>
    </p>
</div>
<div id="ncw-save">
    <h2 id="ncw-save-head"></h2>
    <p id="ncw-save-body"></p>
</div>
<div id="ncw-error">
    <h2 id="ncw-error-head"></h2>
    <p id="ncw-error-body"></p>
</div>
<div id="ncw-notify">
    <h2 id="ncw-notify-head"></h2>
    <p id="ncw-notify-body"></p>
</div>
<div id="ncw-options">
    <h2 id="ncw-options-head"></h2>
    <p id="ncw-options-body"></p>
    <form id="ncw-options-form" action=""></form>
    <p id="ncw-options-options">
      <button id="ncw-options-yes"><?php print T_('Ok'); ?></button>
      <button id="ncw-options-no"><?php print T_('Cancel'); ?></button>
    </p>
</div>
<div id="ncw-confirm">
    <h2 id="ncw-confirm-head"></h2>
    <p id="ncw-confirm-body"></p>
    <p id="ncw-confirm-options">
      <button id="ncw-confirm-yes"><?php print T_('Yes'); ?></button>
      <button id="ncw-confirm-no"><?php print T_('No'); ?></button>
    </p>
</div>
<div id="ncw-custom" class="ncw-form-dialog">
    <h2 id="ncw-custom-head"></h2>
    <div id="ncw-custom-body"></div>
</div>