<?php
/*
$arr_note = $arr_notecount = array();

$notecount = 0;
foreach ($columns as $values) {
    $key = $values[2];
    $note_name = $key . "_note";
    if (true === isset($labels["compound"][$note_name])) {
        $notecount++;
        $arr_notecount[$key] = ' <sup>' . $notecount . '</sup>';
        $arr_note[$key] = '<sup>' . $notecount . '</sup> ' .  str_replace(array('<P>', '</P>'), '', trim($labels["compound"][$note_name])) . '<br />';
    }
}*/
?>