<div class="ncw-left">
    <div class="ncw-accordion">
        <h3 class="ncw-accordion-header current"><?php print T_('Contentbox'); ?></h3>
        <div class="ncw-accordion-content ncw-accordion-current">
            <p class="ncw-accordion-content-part-dark">
                <a href="javascript: ncw.wcms.contentboxgroup.loadNew();" class="ncw_text_button_add"><?php print T_('New contentbox group'); ?></a>
            </p>
            <div class="ncw-contentboxgroup-tree ncw-tree"></div>
        </div>
    </div>
</div>
<div class="ncw-right"></div>
<script type="text/javascript">
ncw.wcms.contentboxgroup();
</script>