<div class="ncw-main-tabs">
    <ul class="ncw-main-tabs-container">
        <li class="ncw-main-tab"><a href="#"><?php print T_('Edit contentboxgroup'); ?></a></li>
    </ul>
    <div class="ncw-main-tab-contents">
        <div class="ncw-main-tab-content">
            <?php print $this->form->create('ncw-contentboxgroup', array('onsubmit' => 'return false;')); ?>
            <?php print $this->form->input("id", array('type' => 'hidden', 'value' => $this->contentboxgroup_id)); ?>
            <?php print $this->form->input('name', array('maxlength' => 100, 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Name')))); ?>
            <div class="ncw-input-container">
                <label for="contentboxgroup_parent_id" class="ncw-label"><?php print T_('Parent contentboxgroup'); ?></label>
                <select id="contentboxgroup_parent_id" name="data[Contentboxgroup][parent_id]" class="ncw-select">
                    <?php print $this->groups_options; ?>
                </select>
            </div>
            <?php print $this->form->end(); ?>
        </div>
    </div>
</div>
<div class="ncw-status-action-bar">
    <div class="ncw-status-message"></div>
    <ul class="ncw-actions">
        <li class="ncw-action"><a href="#" rel="wcms/contentboxgroup" class="ncw-delete-trigger-ajax ncw_delete_icon"><?php print T_('Delete'); ?></a></li>
        <li class="ncw-action"><a href="#" rel="wcms/contentboxgroup" class="ncw-save-trigger-ajax ncw_save_icon"><?php print T_('Save'); ?></a></li>
    </ul>
</div>
