<div class="ncw-left">
	<div class="ncw-accordion">
        <h3 class="ncw-accordion-header current"><?php print T_('Feed Management'); ?></h3>
        <div class="ncw-accordion-content ncw-accordion-current">
            <p class="ncw-accordion-content-part-dark">
                <a href="<?php print $this->html->url(array('action' => 'new')); ?>" class="ncw_text_button_add"><?php print T_('New Feed'); ?></a>
            </p>   
        </div>
    </div>	
</div>
<div class="ncw-right">
		<div class="ncw-main-tabs">
        <ul class="ncw-main-tabs-container">
        	<li class="ncw-option-tab"><a href="<?php print $this->html->url(array('action' => 'all')); ?>"><?php print T_('Back'); ?></a></li>
            <li class="ncw-main-tab"><a href="#"><?php print T_('New Feed'); ?></a></li>
        </ul>
        <div class="ncw-main-tab-contents">
            <div class="ncw-main-tab-content">
            	<?php print $this->form->create('ncw-feed'); ?>
            	
                <?php print $this->form->input("name", array('maxlength' => 100, 'title' => T_('Name of the feed'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Name of the feed')))); ?>
            	
            	<?php print $this->form->end(); ?>
            </div>
        </div>
    </div>
	<div class="ncw-status-action-bar">
	    <div class="ncw-status-message"></div>
	    <ul class="ncw-actions">
	        <li class="ncw-action"><a href="#" rel="core/feed" class="ncw-new-trigger-ajax ncw_save_icon"><?php print T_('Save')?></a></li>
	    </ul>
	</div>      
</div>          	