<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Netzcraftwerk 3.0 :: error</title>
		<link rel="stylesheet" type="text/css" href="themes/nice_and_friendly/web/css/layout.css" media="screen" />
	</head>
	<body class="ncw3">
		<h1>Error</h1>
		<p><?php print $this->message; ?></p>
		<br />
		<pre id="ncw3-trace"><?php print $this->getTraceAsString() ;?></pre>
	</body>
</html>