<?php

$url_pdb = Ncw_Configure::read('Project.url');
$add_to_url = '?';
$i = 0;
foreach ($_GET as $key => $value) {
	if ($key == 'SID' || $key == 'CID') {
		// if ($true == strstr($add_to_url, "?")) {
		$add_to_url .= '&';
		// } else {
		//	$add_to_url .= '?';
		// }
		$add_to_url .= $key . '=' . $value;
	}

	$i++;
}

$series_tmp = array();
foreach ($series As $serie) {
	$serie['mysort'] = $serie['brand']['sort'] . $serie['name'];
	$serie['mysort2'] = $serie['name'];
	$series_tmp[] = $serie;
}
$keys = array_column($series_tmp, 'mysort');
array_multisort($keys, SORT_ASC, $series_tmp);

$series = $series_tmp;

?>
<!-- serie_search.phtml -->
<style>
	.readmore-button{
		border: 0;
    background: #fff;
    color: #224d8f;
    font-size: 16px;
    width: 80px;
    float: left;
    text-align: left;
    padding: 0;	
	}
</style>
	 <div class="pdb2_search_headline">
		 <h1>
			 <?php print Wcms_ContentboxController::getContenbox('find-the-right-product', $language_id); ?>
		 </h1>
		<?php print Wcms_ContentboxController::getContenbox('pdb---search---info', $language_id); ?>
		<?php
		// if ($_SERVER['REMOTE_ADDR'] == '87.148.4.155') {
		?>
		 		<div class="disclaimer-preview" style="display: block; margin-top: 30px;">
					<?php
					if ($language_id == 10) {
						print substr(Wcms_ContentboxController::getContenbox('disclaimer-l', $language_id), 0, 260);
					} else {
						print substr(Wcms_ContentboxController::getContenbox('disclaimer-l', $language_id), 0, 256);
					}
					// echo $language_id;
					?>
					 ...
					 <br /><input type="button" class="readmore-button"  onclick="opendisclaimer();" value="<?php print Wcms_ContentboxController::getContenbox('read-more', $language_id); ?>" >
		 		</div>
		 		<div class="disclaimer-full" style="display: none; margin-top: 30px;">
					<?php print Wcms_ContentboxController::getContenbox('disclaimer-l', $language_id); ?>
		 		</div>
			<?php
			// }
			?>
		 
</div>
   <div class="pdb2_search_list">
    <!--<div id="ergebniss_header"><h3><?php print Wcms_ContentboxController::getContenbox('pdb---search---search-results', $language_id); ?></h3></div>-->
		<?php
		$counter = 1;

		if (count($series) > 0) {
			?>
    <table class="pdb-list-search" cellspacing="0" cellpadding="0">
			<input class="pdb2-label-input-search-results" type="hidden" value="<?php print Wcms_ContentboxController::getContenbox('pdb---search---search-results', $language_id); ?>" />
    	<thead>
    		<tr class="headline ">
        <th width="20%"><?php print Wcms_ContentboxController::getContenbox('pdb---series', $language_id); ?></th>
        <th class="pdb-list-search-small-hide"><?php print Wcms_ContentboxController::getContenbox('description', $language_id); ?></th>
        <th width="20%"><?php print Wcms_ContentboxController::getContenbox('pdb---brand', $language_id); ?></th>
        </tr>
       </thead>
			<tbody>
        <?php

		/*
		 * Prüft ob die Serie ein Compound hat es wird entweder 0 oder 1 zurückgegeben
		 */
		function checkSeriesCompoundsCount($serie_id)
		{
			$obj_ax = new Tpepdb2_AjaxController();
			$counter = $obj_ax->countCompoundSeries($serie_id);
			return $counter;
		}

		foreach ($series as $serie) {
			$counter = checkSeriesCompoundsCount($serie['id']);

			if ($serie['pdb20'] == 1 && $counter > 0) {  // Nur noch neue Serien Ausgeben
				?>
						<tr>
							<td class="name">
								 <a href="<?php print $url_pdb . $add_to_url . ''; ?>&amp;sid=<?php print $serie['id']; ?><?php if ($language == 'it') { ?>&amp;ls=it<?php } ?><?php if ($language == 'pl') { ?>&amp;ls=pl<?php } ?>" target="_self"><?php print $serie['name']; ?></a>
							</td>
							<td class="pdb-list-search-small-hide">
									<?php if (true === isset($serie['text1'])) { print $serie['text1']; } ?>
							</td>
							<?php
							if ($language_id != 3 || strlen($serie['brand']['name_zh']) < 1) {  // 3 ist Chinesisch und soll den eintrag name_zh benutezn
								?>
								<td style="white-space: nowrap"><?php print str_replace('®', '<sup>®</sup>', $serie['brand']['name']); ?></td>
							<?php } else { ?>
								<td style="white-space: nowrap"><?php print str_replace('®', '<sup>®</sup>', $serie['brand']['name_zh']); ?></td>
							<?php } ?>
						</tr>

					<?php
				$counter++;
			}  // If serie PDB20
		}
		?>
				</tbody>
    </table>
    <?php } ?>
	    
	   </div>
   <!--</div>
 </div>
</section>-->