<div class="ncw-right">
    <div class="ncw-main-tabs">
        <ul class="ncw-main-tabs-container">
            <li class="ncw-main-tab"><a href="#"><?php print T_('Overview'); ?></a></li>
        </ul>
        <div class="ncw-main-tab-contents">
            <div class="ncw-main-tab-content">
                <?php print $this->html->link(T_('Import'), array('controller' => 'import', 'action' => 'index')); ?>
            </div>
        </div>
    </div>
    <div class="ncw-status-action-bar">
    </div>
</div>