<div class="ncw-right">
    <div class="ncw-main-tabs">
        <ul class="ncw-main-tabs-container">
            <li class="ncw-main-tab"><a href="#"><?php print T_('Profile of'); ?> <?php print $this->username; ?></a></li>
        </ul>
        <div class="ncw-main-tab-contents">
            <div class="ncw-main-tab-content">
                <?php print T_('This is your profile page. You can set a new profile password if you want to.'); ?><br />
                <br />
                <?php print $this->form->create(); ?>
                <?php print $this->form->input("language_id", array("type" => "hidden", "options" => $this->languages, 'title' => T_('Language'), 'class' => 'ncw-select', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Language')))); ?>
                <?php if (true === $this->contact_module) { ?>
                    <?php
                    $contact_label = '';
                    if ($this->contact_id > 0) { ?>
						<div class="ncw-input-container">
							<div class="ncw-label"><?php print T_('Contact'); ?></div>
							<?php print $this->html->link($this->contact_name, array('module' => 'contacts', 'controller' => 'contact', 'action' => 'edit', 'id' => $this->contact_id), array('target' => '_blank')); ?>
						</div>						
						<?php
                    }
                    ?>
                <?php } ?>  
                <p>
                	<?php print T_('Password:'); ?>
                </p>              
                <?php print $this->form->input("password", array('type' => 'password', 'maxlength' => 20, 'title' => T_('The new password must contain at least 6 characters. One of them must be a number or a special character'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Password')))); ?>
                <?php print $this->form->input("password2", array('type' => 'password', 'maxlength' => 20, 'title' => T_('Repeat Password'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Repeat Password')))); ?>
                <?php print $this->form->input("password3", array('type' => 'password', 'maxlength' => 20, 'title' => T_('Old Password'), 'class' => 'ncw-input', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Old Password')))); ?>
                <?php print $this->form->end(); ?>
            </div>
        </div>
    </div>
    <div class="ncw-status-action-bar">
        <div class="ncw-status-message"></div>
        <ul class="ncw-actions">
            <li class="ncw-action"><a href="#" class="ncw-save-trigger ncw_save_icon"><?php print T_('Save'); ?></a></li>
        </ul>
    </div>
</div>
