<?php print $this->element('transfer_menu'); ?>
<div class="ncw-right">
    <div class="ncw-main-tabs">
        <ul class="ncw-main-tabs-container">
            <li class="ncw-main-tab"><a href="#"><?php print T_('Export as CSV-File'); ?></a></li>
        </ul>
        <div class="ncw-main-tab-contents">
            <div class="ncw-main-tab-content">
                <?php print $this->form->create('ncw-contact-exportcsv', array('onsubmit' => 'return false;', 'action' => $this->html->url(array('action' => 'createCsv')))); ?>
                
                <h2><?php echo T_('Which group do you want to export?'); ?></h2>
                <?php print $this->form->input('group_id', array('type' => 'select', 'options' => $this->arr_groups, 'title' => T_('Groups'), 'class' => 'ncw-select', 'div' => array('class' => 'ncw-input-container'), 'label' => array('class' => 'ncw-label', 'text' => T_('Groups')))); ?>
                
                <?php print $this->form->end(); ?>
            </div>
        </div>
    </div>
    <div class="ncw-status-action-bar">
        <div class="ncw-status-message"></div>
        <ul class="ncw-actions">
			<li class="ncw-action"><a href="javascript: $('#ncw-contact-exportcsv_form').submit(); " class="ncw_import_icon"><?php echo T_('Export'); ?></a></li>
        </ul>
    </div>       
</div>