<!--TRENNER-->
</article>
 
  

        

<!--<script src="<?php echo $url_website; ?>/core/assets/vendor/domready/ready.min.js?v=1.0.8"></script>
<script src="<?php echo $url_website; ?>/core/assets/vendor/jquery/jquery.min.js?v=3.2.1"></script>-->
<?php if ($_GET['sid'] > 0 || $_GET['cid'] > 0) {?>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
<?php } ?>
<!---->
<!--
<script src="<?php print $this->base; ?>assets/tpepdb2/javascript/config.js?time=<?php echo date('mdH'); ?>" type="text/javascript"></script>
	<script src="<?php print $this->base; ?>assets/tpepdb2/javascript/main.js?time=<?php echo date('mdH'); ?>" type="text/javascript"></script>-->

<!--<script src="<?php print $this->base; ?>/assets/wcms/javascript/tpe_scripts.20100609.js?time=<?php echo date('mdH'); ?>" type="text/javascript"></script>-->
<!--<script src="<?php echo $url_website; ?>/core/assets/vendor/underscore/underscore-min.js?v=1.8.3"></script>
<script src="<?php echo $url_website; ?>/core/assets/vendor/jquery-once/jquery.once.min.js?v=2.2.0"></script>-_>
<!--<script src="<?php echo $url_website; ?>/core/misc/drupalSettingsLoader.js?v=8.4.3"></script>
<script src="<?php echo $url_website; ?>/core/misc/drupal.js?v=8.4.3"></script>
<script src="<?php echo $url_website; ?>/core/misc/drupal.init.js?v=8.4.3"></script>
<script src="<?php echo $url_website; ?>/themes/bootstrap/js/drupal.bootstrap.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/bootstrap/js/attributes.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/bootstrap/js/theme.js?p27ht0"></script>-->
<!--<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/affix.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/alert.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/button.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/carousel.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/collapse.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/dropdown.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/modal.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/tooltip.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/popover.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/scrollspy.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/tab.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/bootstrap/assets/javascripts/bootstrap/transition.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/js/plugins/datetime-picker/datetime-picker.min.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/js/plugins/lightgallery/lightgallery-all.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/js/plugins/slick/slick.min.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/js/plugins/datetime-picker/init.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/js/plugins/lightgallery/init.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/js/plugins/slick/init.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/js/plugins/browser/jquery.browser.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/js/plugins/device/device.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/js/plugins/skrollr/skrollr.js?p27ht0"></script>
<script src="<?php echo $url_website; ?>/themes/kraiburg/js/plugins/textfield-autogrow/autogrow.js?p27ht0"></script>-->


<!--<script src="<?php print $this->base; ?>/assets/wcms/js/swiper.min.js"></script>-->

<!--<script src="<?php echo $url_website; ?>/themes/kraiburg/js/kraiburg.js?p27ht0"></script>-
<script src="<?php echo $url_website; ?>/themes/kraiburg/js/main.js?p27ht0"></script>
<!--<script src="/modules/contrib/form_placeholder/js/form_placeholder.js?v=8.4.3"></script>-->
<?php
//include('_language_switch.php');
?>



  </body>
</html>
