
<!DOCTYPE html>
<html lang="en" dir="ltr" prefix="content: http://purl.org/rss/1.0/modules/content/  dc: http://purl.org/dc/terms/  foaf: http://xmlns.com/foaf/0.1/  og: http://ogp.me/ns#  rdfs: http://www.w3.org/2000/01/rdf-schema#  schema: http://schema.org/  sioc: http://rdfs.org/sioc/ns#  sioct: http://rdfs.org/sioc/types#  skos: http://www.w3.org/2004/02/skos/core#  xsd: http://www.w3.org/2001/XMLSchema# ">
  <head>
    <meta charset="utf-8" />
<meta name="Generator" content="Drupal 8 (https://www.drupal.org)" />
<meta name="MobileOptimized" content="width" />
<meta name="HandheldFriendly" content="true" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="shortcut icon" href="/themes/kraiburg/favicon.ico" type="image/vnd.microsoft.icon" />
<link rel="alternate" hreflang="en" href="http://neu.kraiburg-tpe.com/en/404" />
<link rel="canonical" href="/en/404" />
<link rel="shortlink" href="/<?php print $site['shortcut']; ?>/products/product-database" />
<link rel="revision" href="/en/404" />

    <title>PDB | Kraiburg</title>
    
<?php 

$url_website = 'http://neu.kraiburg-tpe.com';
$url_pdb = 'http://www.kraiburg-tpe.com/pdb/';


?>
    
    <link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/align.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/fieldgroup.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/container-inline.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/clearfix.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/details.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/hidden.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/item-list.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/js.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/nowrap.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/position-container.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/progress.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/reset-appearance.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/resize.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/sticky-header.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/system-status-counter.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/system-status-report-counters.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/system-status-report-general-info.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/tablesort.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/tree-child.module.css?p27ht0" media="all" />

<link rel="stylesheet" href="<?php print $this->base; ?>/assets/wcms/css/font-awesome.min.css?p27ht0" media="all" />

<link rel="stylesheet" href="<?php echo $url_website; ?>/themes/kraiburg/css/style.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php print $this->base; ?>/assets/wcms/css/kraiburg.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php print $this->base; ?>/assets/wcms/css/tpe.css?time=<?php echo date('ymdhis'); ?>" media="all" />
<!--<link rel="stylesheet" href="<?php print $this->base; ?>/assets/wcms/css/style2.css?p27ht0" media="all" />-->
<link rel="stylesheet" href="<?php echo $url_website; ?>/themes/kraiburg/css/fixes.css?p27ht0" media="all" />
<!--<link rel="stylesheet" href="<?php echo $url_website; ?>/themes/kraiburg/css/admin.css?p27ht0" media="all" />-->

    
<!--[if lte IE 8]>
<script src="/core/assets/vendor/html5shiv/html5shiv.min.js?v=3.7.3"></script>
<![endif]-->

  </head>
  <body class="cssAnimate smartwatch navigation-wide path-node page-node-type-page drone">
        <a href="#main-content" class="visually-hidden focusable skip-link">
      Skip to main content
    </a>
    
    
<div id="ct-js-wrapper" class="ct-js-wrapper ct-pageWrapper">

          <nav data-background="#ffffff" data-height="80" class="navbar navbar-default navbar-fixed navbar-desktop navbar-wide shrink">
    <div class="navbar-header">
            <a class="navbar-brand" href="/en" title="Home" rel="home">
      <div class="inner"><img src="<?php echo $url_website; ?>/themes/kraiburg/logo.svg" alt="Home"/></div>
    </a>
                  <ul block="block-kraiburg-main-menu" class="menu nav navbar-nav ct-navbar--fadeIn" role="menu">
                                    <li class="nav-item">
        <a href="/en" data-drupal-link-system-path="&lt;front&gt;">Home</a>
                  </li>
                                    <li class="expanded dropdown active nav-item">
        <a href="/en" class="dropdown-toggle" data-target="#" data-toggle="dropdown">Kraiburg TPE</a>
                                  <ul block="block-kraiburg-main-menu" class="menu ct-navbar--fadeIn dropdown-menu" role="menu">
        <div class="top_arrow_subnav"></div>
                                      <div class="two-column_subnav">
                <li class="nav-item">
        <a href="/en" title="New description for this item" data-drupal-link-system-path="&lt;front&gt;">Value added services</a>
                  </li>
              <p class="dropdown-description">New description for this item</p>
        <a href="/en" title="New description for this item" class="btn btn-transparent btn--withIcon btn--motiveColor" data-drupal-link-system-path="&lt;front&gt;">Read more</a>
        </div>
                                              <div class="two-column_subnav">
                <li class="active nav-item">
        <a href="/en/sustainability" data-drupal-link-system-path="node/23" class="is-active">Sustainability</a>
                  </li>
                    </div>
              </ul>
  
            </li>
                                    <li class="expanded dropdown nav-item">
        <a href="/en" class="dropdown-toggle" data-target="#" data-toggle="dropdown">Markets</a>
                                  <ul block="block-kraiburg-main-menu" class="menu ct-navbar--fadeIn dropdown-menu" role="menu">
        <div class="top_arrow_subnav"></div>
                                      <div class="two-column_subnav">
                <li class="nav-item">
        <a href="/en" title="Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa." data-drupal-link-system-path="&lt;front&gt;">Automotive</a>
                  </li>
              <p class="dropdown-description">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.</p>
        <a href="/en" title="Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa." class="btn btn-transparent btn--withIcon btn--motiveColor" data-drupal-link-system-path="&lt;front&gt;">Read more</a>
        </div>
                                              <div class="two-column_subnav">
                <li class="nav-item">
        <a href="/en/consumer" data-drupal-link-system-path="node/45">Consumer</a>
                  </li>
                                            <li class="nav-item">
        <a href="/en/industry" data-drupal-link-system-path="node/43">Industry</a>
                  </li>
                                            <li class="nav-item">
        <a href="/en/medical" data-drupal-link-system-path="node/44">Medical</a>
                  </li>
                    </div>
              </ul>
  
            </li>
                                            <li class="nav-item">
        <a href="/en/products" data-drupal-link-system-path="node/30">Products</a>
                  </li>
                                            <li class="nav-item">
        <a href="/en" data-drupal-link-system-path="&lt;front&gt;">Product Database</a>
                  </li>
                                    <li class="expanded dropdown nav-item">
        <a href="/en" class="dropdown-toggle" data-target="#" data-toggle="dropdown">Media</a>
                                  <ul block="block-kraiburg-main-menu" class="menu ct-navbar--fadeIn dropdown-menu" role="menu">
        <div class="top_arrow_subnav"></div>
                                      <div class="two-column_subnav">
                <li class="nav-item">
        <a href="/en" data-drupal-link-system-path="&lt;front&gt;">Press Releases</a>
                  </li>
              <p class="dropdown-description"></p>
        <a href="/en" class="btn btn-transparent btn--withIcon btn--motiveColor" data-drupal-link-system-path="&lt;front&gt;">Read more</a>
        </div>
                    </ul>
  
            </li>
                    </ul>
  

      
        <ul block="block-socials" class="ct-socials ct-socials--motive list-unstyled list-inline">
                <li>
        <a href="/en" data-toggle="tooltip" data-placement="bottom" title="Careers" data-drupal-link-system-path="&lt;front&gt;"><i class="icon-Careers"></i></a>
      </li>
                <li>
        <a href="/en" data-toggle="tooltip" data-placement="bottom" title="News" data-drupal-link-system-path="&lt;front&gt;"><i class="icon-News"></i></a>
      </li>
                <li>
        <a href="/en" data-toggle="tooltip" data-placement="bottom" title="Contact" data-drupal-link-system-path="&lt;front&gt;"><i class="icon-contact"></i></a>
      </li>
        </ul>
  


    <div class="ct-iconBox ct-iconBox--small ct-lang-link media">
    <a href="#">
      <div class="media-left">
        <div class="ct-iconBox-icon">
          <i class="icon-Sprache"></i>
        </div>
      </div>
      <div class="media-body">
        <h6 class="ct-iconBox-title"><?php print $language_code; ?></h6>
      </div>
    </a>
  </div>

    </div>
    <div class="ct-search-link">
      <a href="#">
        <i class="fa fa-search"></i>
      </a>
    </div>
  </nav>

  
        <div role="main" class="main-container js-quickedit-main-content">

                              <div class="highlighted">  <div class="region region-highlighted">
    

  </div>
</div>
              
            
                    <a id="main-content"></a>
          <div class="region region-content">
      <article data-history-node-id="23" role="article" about="/en/sustainability" typeof="schema:WebPage" class="page full clearfix">

  
      <span property="schema:name" content="SUSTAINABILITY" class="hidden"></span>


  
  <div class="content">
        <div class="field field--name-field-paragraph field--type-entity-reference-revisions field--label-hidden field__items">
                <div class="field__item">
            <div class="paragraph paragraph--type--title paragraph--view-mode--default" id="title-599564239">
                <header data-background="<?php echo $this->base; ?>/assets/wcms/images/bg-100.jpg" data-height="50%" class="ct-header">
        <div class="headline-container-subheader">
          

  <!--<h3 class="field field--name-field-title field--type-string-long field--label-hidden ct-header-title animated field--item">Product Database</h3>-->

        </div>
      </header>
      </div>

            </div>
            
            
            




