
<!DOCTYPE html>
<html lang="en" dir="ltr" prefix="content: http://purl.org/rss/1.0/modules/content/  dc: http://purl.org/dc/terms/  foaf: http://xmlns.com/foaf/0.1/  og: http://ogp.me/ns#  rdfs: http://www.w3.org/2000/01/rdf-schema#  schema: http://schema.org/  sioc: http://rdfs.org/sioc/ns#  sioct: http://rdfs.org/sioc/types#  skos: http://www.w3.org/2004/02/skos/core#  xsd: http://www.w3.org/2001/XMLSchema# ">
  <head>
    <meta charset="utf-8" />
<meta name="Generator" content="Drupal 8 (https://www.drupal.org)" />
<meta name="MobileOptimized" content="width" />
<meta name="HandheldFriendly" content="true" />
<meta name="viewport" content="user-scalable=no, width=320, initial-scale=0.8" />
<link rel="shortcut icon" href="/neu/themes/kraiburg/favicon.ico" type="image/vnd.microsoft.icon" />
<link rel="alternate" hreflang="en" href="http://kraiburg-tpe.com/neu/en/product-database" />
<link rel="canonical" href="/en/product-database" />
<link rel="shortlink" href="/en/node/57" />
<link rel="revision" href="/en/product-database" />

    <title>PDB | Kraiburg</title>
    
<?php 

$url_website = 'http://www.kraiburg-tpe.com';
$url_pdb = $this->base;


?>
    
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/align.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/fieldgroup.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/container-inline.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/clearfix.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/details.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/hidden.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/item-list.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/js.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/nowrap.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/position-container.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/progress.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/reset-appearance.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/resize.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/sticky-header.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/system-status-counter.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/system-status-report-counters.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/system-status-report-general-info.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/tablesort.module.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/core/modules/system/css/components/tree-child.module.css?p27ht0" media="all" />

    <!--<link rel="stylesheet" href="<?php echo $url_website; ?>/sites/default/files/css/css_mrab1GKFgElx-kxKCNq1SnIWRV-GYZDakUc8CBnGRwo.css?p3omxv" media="all" />
<link rel="stylesheet" href="<?php echo $url_website; ?>/sites/default/files/css/css_jfjBqnrRrJHZF-oy9qaGZjReorXCKhnNBAmbojQMcLs.css?p3omxv" media="all" />-->

<link rel="stylesheet" href="<?php print $this->base; ?>/assets/wcms/css/font-awesome.min.css?p27ht0" media="all" />

<!--<link rel="stylesheet" href="<?php echo $url_website; ?>/themes/kraiburg/css/style.css?p27ht0" media="all" />-->
<link rel="stylesheet" href="<?php print $this->base; ?>/assets/wcms/css/style.css?p27ht0" media="all" />
<link rel="stylesheet" href="<?php print $this->base; ?>/assets/wcms/css/kraiburg.css?p27ht0" media="all" />


<!--<link rel="stylesheet" href="<?php print $this->base; ?>/assets/wcms/css/swiper.min.css">-->

<link rel="stylesheet" href="<?php print $this->base; ?>/assets/wcms/css/tpe.css?time=<?php echo date('ymdhis'); ?>" media="all" />
<!--<link rel="stylesheet" href="<?php print $this->base; ?>/assets/wcms/css/style2.css?p27ht0" media="all" />-->
<!--<link rel="stylesheet" href="<?php echo $url_website; ?>/themes/kraiburg/css/fixes_.css?p27ht0" media="all" />-->
<!--<link rel="stylesheet" href="<?php echo $url_website; ?>/themes/kraiburg/css/admin.css?p27ht0" media="all" />-->

    
<!--[if lte IE 8]>
<script src="/core/assets/vendor/html5shiv/html5shiv.min.js?v=3.7.3"></script>
<![endif]-->

  </head>
  <body class="cssAnimate smartwatch navigation-wide path-node page-node-type-page drone">
    
      <article  role="article" about="/en/product-database" typeof="schema:WebPage" class="page full clearfix">
      <!--TRENNER-->
            
            

