<?php include_once '_head.phtml'; ?>
<div id="article_large">
    <?php if (true === $admin) { ?><div id="ncw-area-1" class="ncw-sortable"><?php } if (true === isset($areas[1])) { foreach ($areas[1] as $area =>  $content) { print $content; } } if (true === $admin) { ?><div class="ncw-area-clear"></div></div><?php } ?>
    <div class="continuous_text">
    <?php $num_articles = 0; $archive = new Wcms_ArchiveController(); foreach($archive->readArticles($site["id"], $language_id, $language_code, $live, $num_articles) as $article) { ?>

<?php
$date = explode('-', $article['date']);
switch ($language_code) {
case 'de':
    $month = array('Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'July', 'August', 'September', 'Oktober', 'November', 'Dezember');
    $time = mktime(0, 0, 0, $date[1], $date[2], $date[0]);
    $date = date('d', $time) . '. ' . $month[date('m', $time) - 1] . ' ' . date('Y', $time);
    break;
case 'zh':
    $date = date('Y年n月d日', mktime(0, 0, 0, $date[1], $date[2], $date[0]));
    break;
case 'fr':
    $date = date('d-m-Y', mktime(0, 0, 0, $date[1], $date[2], $date[0]));
    break;
case 'es':
    $date = date('d/m/Y', mktime(0, 0, 0, $date[1], $date[2], $date[0]));
    break;
default:
    $date = explode('-', $article['date']);
    $date = date('F d, Y', mktime(0, 0, 0, $date[1], $date[2], $date[0]));
}
?>

        <h4><?php print $date; ?></h4>
        <h3><?php print $article["head"]; ?></h3>
        <?php print $article["body"]; ?>
        <a href="<?php print $article["url"]; ?>">...<?php print Wcms_ContentboxController::getContenbox('read-more', $language_id); ?></a><br /><br />
    <?php } ?>
    <?php if ($_GET["as"] > 0) { ?><a href="?as=<?php print $_GET["as"] - 10; ?>&amp;ae=<?php print $_GET["as"]; ?>"><?php print Wcms_ContentboxController::getContenbox('previous', $language_id); ?></a><?php } ?> <?php if (($_GET["ae"] + 10) > $num_articles) { $ae = $num_articles; } else { $ae = $_GET["ae"] + 10; } if ($_GET["ae"] < $num_articles) { ?><a href="?as=<?php print $_GET["ae"]; ?>&amp;ae=<?php print $ae; unset($ae); ?>"><?php print Wcms_ContentboxController::getContenbox('next', $language_id); ?></a><?php } ?>
</div>
</div>
<div id="aside_right">
    <?php 
    //if ($_SERVER['REMOTE_ADDR'] == '84.145.4.211' || $_SERVER['REMOTE_ADDR'] =='212.68.121.65') {
        include_once '_contact_box.phtml';
    //} else {
    //     include_once '_search_news.phtml';   
    //}
    ?>
    <?php if (true === $admin) { ?><div id="ncw-area-2" class="ncw-sortable"><?php } if (true === isset($areas[2])) { foreach ($areas[2] as $area =>  $content) { print $content; } } if (true === $admin) { ?><div class="ncw-area-clear"></div></div><?php } ?>
    <?php include_once '_toolbox_login.phtml'; ?>
</div>
<?php include_once '_footer.phtml'; ?>