<?php include_once '_head.phtml'; ?>
<div id="article_large">
    {area.1.Main}
</div>
<div id="aside_right">
    <?php
    //if ($_SERVER['REMOTE_ADDR'] == '84.145.4.211' || $_SERVER['REMOTE_ADDR'] =='212.68.121.65') {
        include_once '_contact_box.phtml';
    //} else {
    //     include_once '_search_news.phtml';   
    //}
    ?>
    {area.2.Aside}
    <?php include_once '_toolbox_login.phtml'; ?>
</div>
<?php include_once '_footer.phtml'; ?>

{subarea.define.8.Press Gallery}