<?php if (true === isset($_GET['key']) && $_GET['key'] == 'skd8m3m48') { 
$pdb = true;
?>
<?php include_once '_head.phtml'; ?>
<div id="article_large">
    {article}
</div>
<div id="aside_right">
    <?php include_once '_search_news.phtml'; ?>     
    {side}
    <?php include_once '_toolbox_login.phtml'; ?> 
</div>
<?php include_once '_footer.phtml'; ?>     
<?php } else { ?>    
<?php $this->_error404(); ?>
<? } ?>
