<?php include_once '_head.phtml'; ?>
<div id="article_large">
  {area.begin.1.Main}
   {area.contents.1}
    {area.content}
   {/area.contents}
   <div class="clear twenty"></div>
  {/area.begin}
  {area.3}
</div>
<div id="aside_right">
    <?php include_once '_search_news.phtml'; ?>
    {area.2.Aside}
    <?php include_once '_toolbox_login.phtml'; ?> 
</div>
<?php include_once '_footer.phtml'; ?>