<div class="ncw-left">
    <div class="ncw-accordion">
        <h3 class="ncw-accordion-header current"><?php print T_('Options'); ?></h3>
        <div class="ncw-accordion-content ncw-accordion-current">
            <?php if (true === $this->permissions['/wcms/news/new']) { ?>
                <p class="ncw-accordion-content-part-dark">
                    <?php print $this->html->link(T_('New'), array('action' => 'new'), array('class' => 'ncw_text_button_add')); ?>
                </p>
            <?php } ?>
        </div>
    </div>
</div>
<div class="ncw-right">
    <div class="ncw-main-tabs">
        <ul class="ncw-main-tabs-container">
            <li class="ncw-main-tab"><a href="#"><?php print T_('Library'); ?></a></li>
        </ul>
        <div class="ncw-main-tab-contents">
            <div class="ncw-main-tab-content">
                <p>
                    <span class="ncw-new"><?php print T_('new'); ?></span>
                    <span class="ncw-modified"><?php print T_('modified'); ?></span>
                    <span class="ncw-published"><?php print T_('published'); ?></span>
                </p>
                <table class="ncw-table">
                    <thead>
                        <tr>
                            <th><?php print T_('Name'); ?></th>
                            <th><?php echo T_('Languages'); ?></th>
                            <th><?php print T_('Options'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (true === is_array($this->news)) { ?>
                            <?php foreach ($this->news as $news) { ?>
                                <tr>
                                    <td>
                                        <?php print $this->html->link($news->getNameEncoded(), array("action" => "edit", "id" => $news->getId()), array('class' => 'ncw-' . $news->getStatus())); ?>
                                    </td>
                                    <td class="ncw-table-td-icons">
                                        <?php
                                        if (true === isset($this->arr_languages[$news->getId()])) {
                                            foreach ($this->arr_languages[$news->getId()] as $language) {
                                        ?>
                                                <?php print $this->html->image("country_flags/" . $language['shortcut'] . ".gif", false, array("alt" => $language['name'], "title" => $language['name'])); ?>
                                        <?php
                                            }
                                        } else {
                                        ?>
                                        &nbsp;
                                        <?php } ?>
                                    </td>
                                    <td class="ncw-table-td-icons">
                                        <?php if (true === $this->permissions['/wcms/news/edit']) { ?>
                                            <?php print $this->html->link($this->html->image("icons/16px/pencil.png", false, array('alt' => T_('edit'), 'title' => T_('edit'))), array("action" => "edit", "id" => $news->getId()), null, false, false); ?>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>