<?php print $this->html->docType(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php print $this->html->charset(Ncw_Configure::read('App.encoding')); ?>
        <meta http-equiv="Content-language" content="en" />
        <title>Netzcraftwerk 3.0 :: <?php print $this->page_title; ?></title>
        <?php print $this->html->css('login', null, array('media' => 'screen')); ?>
        <?php print $this->html->meta('icon', 'favicon.ico', array('type' => 'icon')); ?>
        <?php print $this->javascript->link('lib/jquery-1.4.2.min.js'); ?>
    </head>
    <body class="ncw">
        <div id="ncw-shell">
            <?php print $this->html->image('logo-big.png', false, array('id' => 'ncw-logo')); ?>
            <?php print $this->view; ?>
        </div>
    </body>
    <script type="text/javascript">
      var $buoop = {vs:{i:6,f:1.5,o:9.64,s:2,n:9}}
      $buoop.ol = window.onload;
      window.onload=function(){
       if ($buoop.ol) $buoop.ol();
       var e = document.createElement("script");
       e.setAttribute("type", "text/javascript");
       e.setAttribute("src", "http://browser-update.org/update.js");
       document.body.appendChild(e);
      }
      window.onload = function(){
        var text_input = document.getElementById ("user_name");
        text_input.focus ();
        text_input.select ();
      }
    </script>
</html>